### ISSUE TITLE
Sensu client crashes -- unicode issue?

### ISSUE THREAD

**Issue by ctheune** [sensu/sensu#1001]
Sensu client is exiting on me with this:

```
Jul 20 19:37:37 cecil sensu-client[32374]: {"timestamp":"2015-07-20T19:37:37.297871+0200","level":"info","message":"publishing check result","payload":{"client":"cecil","check":{"name":"check_1.bp.blogspot.com","issued":1437413851,"command":"check_http 1.bp.blogspot.com","executed":1437413851,"duration":6.117,"output":"HTTP OK: HTTP/1.0 302 Found - 521 bytes in 0.062 second response time |time=0.061670s;;;0.000000 size=521B;;;0\n","status":0}}}
Jul 20 19:37:37 cecil sensu-client[32374]: {"timestamp":"2015-07-20T19:37:37.303649+0200","level":"warn","message":"reconnecting to transport"}
Jul 20 19:37:37 cecil sensu-client[32374]: /nix/store/kpvp7f126ssxzcygg3y1hq9hb00sa6k5-sensu-0.20.0/lib/ruby/gems/2.2.2/gems/multi_json-1.11.2/lib/multi_json/adapters/json_common.rb:19:in `encode': "\xC4" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
Jul 20 19:37:37 cecil sensu-client[32374]: from /nix/store/kpvp7f126ssxzcygg3y1hq9hb00sa6k5-sensu-0.20.0/lib/ruby/gems/2.2.2/gems/multi_json-1.11.2/lib/multi_json/adapters/json_common.rb:19:in `to_json'
Jul 20 19:37:37 cecil sensu-client[32374]: from /nix/store/kpvp7f126ssxzcygg3y1hq9hb00sa6k5-sensu-0.20.0/lib/ruby/gems/2.2.2/gems/multi_json-1.11.2/lib/multi_json/adapters/json_common.rb:19:in `dump'
Jul 20 19:37:37 cecil sensu-client[32374]: from /nix/store/kpvp7f126ssxzcygg3y1hq9hb00sa6k5-sensu-0.20.0/lib/ruby/gems/2.2.2/gems/multi_json-1.11.2/lib/multi_json/adapter.rb:25:in `dump'
Jul 20 19:37:37 cecil sensu-client[32374]: from /nix/store/kpvp7f126ssxzcygg3y1hq9hb00sa6k5-sensu-0.20.0/lib/ruby/gems/2.2.2/gems/multi_json-1.11.2/lib/multi_json.rb:136:in `dump'
Jul 20 19:37:37 cecil sensu-client[32374]: from /nix/store/kpvp7f126ssxzcygg3y1hq9hb00sa6k5-sensu-0.20.0/lib/ruby/gems/2.2.2/gems/sensu-logger-1.0.0/lib/sensu/logger/stream.rb:127:in `create_log_event'
Jul 20 19:37:37 cecil sensu-client[32374]: from /nix/store/kpvp7f126ssxzcygg3y1hq9hb00sa6k5-sensu-0.20.0/lib/ruby/gems/2.2.2/gems/sensu-logger-1.0.0/lib/sensu/logger/stream.rb:51:in `add'
Jul 20 19:37:37 cecil sensu-client[32374]: from /nix/store/kpvp7f126ssxzcygg3y1hq9hb00sa6k5-sensu-0.20.0/lib/ruby/gems/2.2.2/gems/sensu-logger-1.0.0/lib/sensu/logger/stream.rb:31:in `block (2 levels) in create_level_methods'
```

I guess that's a bug ... :)

**Comment by portertech** [comment]
@ctheune what platform are you running the Sensu client on?

**Comment by ctheune** [comment]
This is Linux (NixOS). Any more specifics about the environment you'd need?

**Comment by portertech** [comment]
Using the Sensu package or another installation method? Could be the version of Ruby.

**Comment by ctheune** [comment]
I'm doing the packaging here, NixOS is a bit exotic from the default package perspective. I'm linking it against ruby-2.2.2-p0/bin/ruby

I extracted all other dependencies from your Gemfile, the only thing I changed was the dependency on eventmachine to update to 1.0.7 because the older ones wouldn't build any longer. 

Let me know if I should get you any other data.

**Comment by portertech** [comment]
@ctheune would it be possible to use the same Ruby as the Sensu omnibus packages? https://github.com/sensu/sensu-build/blob/master/recipes/ruby.rake#L3

**Comment by ctheune** [comment]
Compiling with 2.0 is not a problem. Not the same patch level, probably, but I've got it running. I'm currently trying to reproduce reliably (which likely means I'll have to synthesize a URL to force check_http to create that non-ASCII output). Or probably just a script that outputs unicode. Hmm. 

I'll try that later today if I have time.

**Comment by ctheune** [comment]
Alright. Sorry this took so long:

Here's the log output:

```
Dec 30 10:05:23 cecil sensu-client[7806]: {"timestamp":"2015-12-30T10:05:23.795666+0100","level":"debug","message":"attempting to execute check command","check":{"notification":"Unicode problem","command":"/home/ctheune/check_unicode","interval":10,"standalone":true,"name":"unicode","issued":1451466323}}
Dec 30 10:05:23 cecil sensu-client[7806]: {"timestamp":"2015-12-30T10:05:23.808997+0100","level":"warn","message":"reconnecting to transport"}
Dec 30 10:05:23 cecil sensu-client[7806]: /nix/store/rvdnkv4qs7i4anaf340zflz8xhjgpcr0-sensu-0.21.0/lib/ruby/gems/2.0.0/gems/multi_json-1.11.2/lib/multi_json/adapters/json_common.rb:19:in `encode': "\xC3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
Dec 30 10:05:23 cecil sensu-client[7806]: from /nix/store/rvdnkv4qs7i4anaf340zflz8xhjgpcr0-sensu-0.21.0/lib/ruby/gems/2.0.0/gems/multi_json-1.11.2/lib/multi_json/adapters/json_common.rb:19:in `to_json'
Dec 30 10:05:23 cecil sensu-client[7806]: from /nix/store/rvdnkv4qs7i4anaf340zflz8xhjgpcr0-sensu-0.21.0/lib/ruby/gems/2.0.0/gems/multi_json-1.11.2/lib/multi_json/adapters/json_common.rb:19:in `dump'
Dec 30 10:05:23 cecil sensu-client[7806]: from /nix/store/rvdnkv4qs7i4anaf340zflz8xhjgpcr0-sensu-0.21.0/lib/ruby/gems/2.0.0/gems/multi_json-1.11.2/lib/multi_json/adapter.rb:25:in `dump'
Dec 30 10:05:23 cecil sensu-client[7806]: from /nix/store/rvdnkv4qs7i4anaf340zflz8xhjgpcr0-sensu-0.21.0/lib/ruby/gems/2.0.0/gems/multi_json-1.11.2/lib/multi_json.rb:136:in `dump'
Dec 30 10:05:23 cecil sensu-client[7806]: from /nix/store/rvdnkv4qs7i4anaf340zflz8xhjgpcr0-sensu-0.21.0/lib/ruby/gems/2.0.0/gems/sensu-logger-1.1.0/lib/sensu/logger/stream.rb:125:in `create_log_event'
Dec 30 10:05:23 cecil sensu-client[7806]: from /nix/store/rvdnkv4qs7i4anaf340zflz8xhjgpcr0-sensu-0.21.0/lib/ruby/gems/2.0.0/gems/sensu-logger-1.1.0/lib/sensu/logger/stream.rb:49:in `add'
Dec 30 10:05:23 cecil sensu-client[7806]: from /nix/store/rvdnkv4qs7i4anaf340zflz8xhjgpcr0-sensu-0.21.0/lib/ruby/gems/2.0.0/gems/sensu-logger-1.1.0/lib/sensu/logger/stream.rb:29:in `block (2 levels) in create_level_methods'
Dec 30 10:05:23 cecil sensu-client[7806]: from /nix/store/rvdnkv4qs7i4anaf340zflz8xhjgpcr0-sensu-0.21.0/lib/ruby/gems/2.0.0/gems/sensu-0.21.0/lib/sensu/client/process.rb:88:in `publish_check_result'
Dec 30 10:05:23 cecil sensu-client[7806]: from /nix/store/rvdnkv4qs7i4anaf340zflz8xhjgpcr0-sensu-0.21.0/lib/ruby/gems/2.0.0/gems/sensu-0.21.0/lib/sensu/client/process.rb:157:in `block in execute_check_command'
Dec 30 10:05:23 cecil sensu-client[7806]: from /nix/store/rvdnkv4qs7i4anaf340zflz8xhjgpcr0-sensu-0.21.0/lib/ruby/gems/2.0.0/gems/em-worker-0.0.2/lib/em/worker.rb:21:in `call'
Dec 30 10:05:23 cecil sensu-client[7806]: from /nix/store/rvdnkv4qs7i4anaf340zflz8xhjgpcr0-sensu-0.21.0/lib/ruby/gems/2.0.0/gems/em-worker-0.0.2/lib/em/worker.rb:21:in `block (2 levels) in do_task'
Dec 30 10:05:23 cecil sensu-client[7806]: from /nix/store/rvdnkv4qs7i4anaf340zflz8xhjgpcr0-sensu-0.21.0/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:968:in `call'
Dec 30 10:05:23 cecil sensu-client[7806]: from /nix/store/rvdnkv4qs7i4anaf340zflz8xhjgpcr0-sensu-0.21.0/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:968:in `run_deferred_callbacks'
Dec 30 10:05:23 cecil sensu-client[7806]: from /nix/store/rvdnkv4qs7i4anaf340zflz8xhjgpcr0-sensu-0.21.0/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
Dec 30 10:05:23 cecil sensu-client[7806]: from /nix/store/rvdnkv4qs7i4anaf340zflz8xhjgpcr0-sensu-0.21.0/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
Dec 30 10:05:23 cecil sensu-client[7806]: from /nix/store/rvdnkv4qs7i4anaf340zflz8xhjgpcr0-sensu-0.21.0/lib/ruby/gems/2.0.0/gems/sensu-0.21.0/lib/sensu/client/process.rb:18:in `run'
Dec 30 10:05:23 cecil sensu-client[7806]: from /nix/store/rvdnkv4qs7i4anaf340zflz8xhjgpcr0-sensu-0.21.0/lib/ruby/gems/2.0.0/gems/sensu-0.21.0/exe/sensu-client:10:in `<top (required)>'
Dec 30 10:05:23 cecil sensu-client[7806]: from /nix/store/rvdnkv4qs7i4anaf340zflz8xhjgpcr0-sensu-0.21.0/bin/sensu-client:21:in `load'
Dec 30 10:05:23 cecil sensu-client[7806]: from /nix/store/rvdnkv4qs7i4anaf340zflz8xhjgpcr0-sensu-0.21.0/bin/sensu-client:21:in `<main>'
```

And here's the script that I use to crash it:

```
#!/home/ctheune/.nix-profile/bin/python2.7
print u'\xce'.encode('utf-8')

```

**Comment by ctheune** [comment]
There's multiple things I find interesting:

a) it happens when creating output, not when reading it. I don't know enough about Ruby but this looks like ruby's internal handling doesn't do properly represent decoded unicode strings as an abstract concept, right?
b) the output assumes that what you read from the client has been ascii. I guess this is traditional Nagios "API".
c) last but most important: sensu shouldn't crash.

In Python when we have specific encoding error handling, where we want continuous operations but also might have "garbagey" input.

Instead of:

```
>>> 'somestring\xc3\x8ewithunpredictablestuff'.decode('ascii')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)
```

We do:

```
>>> 'somestring\xc3\x8ewithunpredictablestuff'.decode('ascii', errors='replace')
u'somestring\ufffd\ufffdwithunpredictablestuff'
```

Which puts special symbols in the place indicating encoding issues. This would allow Sensu, to:

* not crash
* show some hopefully still meaningful data
* inform admins about the encoding issue

Additionally, you could consider supporting UTF-8 as an input format on top of ASCII.

**Comment by jeremybz** [comment]
I have the same problem, which occurs when I include the output of a http check.  When the output contains non-ascii characters, sensu client dies with "json_common.rb:21:in `encode': "\xF8" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)"

**Comment by ctheune** [comment]
As a temporary workaround I'm adding "iconv" around my commands to clean up the output and ensure that its ascii-only.

**Comment by calebhailey** [comment]
At first I thought this might be related to https://github.com/sensu/sensu-settings/pull/11, but it looks like this might be a bug. 

@ctheune, @jeremybz can you confirm this is still an issue w/ [Sensu 0.23, which now ships with an embedded Ruby 2.3][1]. I wonder if underlying Ruby enhancements might have helped us out. :pray: :smile: 

[1]: https://sensuapp.org/docs/0.23/changelog

**Comment by portertech** [comment]
Closing this  one, as Sensu now uses a different JSON parser, and Ruby >= 2.3.

**Comment by ctheune** [comment]
Alright. Installing the 'oj' gem fixes this for me. Yay. \o/
