### ISSUE TITLE
sensu-client crashing (OOM)

### ISSUE THREAD

**Issue by filthyrake** [sensu/sensu#1030]
Seeing this on multiple sensu clients with ~9 checks each.
The sensu-client process begins consuming more and more memory, until it OOMs and crashes.
Ubuntu systems.  Monitored with pidstats to confirm that it is the sensu process itself chewing up all the memory.  Client version 0.20.3.

Log output below:
```
{"timestamp":"2015-08-24T18:14:24.796698+0000","level":"warn","message":"reconnecting to transport"}
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-spawn-1.3.0/lib/sensu/spawn.rb:67:in `block in read_until_eof': failed to allocate memory (NoMemoryError)
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-spawn-1.3.0/lib/sensu/spawn.rb:67:in `loop'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-spawn-1.3.0/lib/sensu/spawn.rb:67:in `read_until_eof'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-spawn-1.3.0/lib/sensu/spawn.rb:100:in `child_process'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-spawn-1.3.0/lib/sensu/spawn.rb:31:in `block in process'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:1037:in `call'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:1037:in `block in spawn_threadpool'
```

Should note, client went from less than 1% memory usage to OOMing in less than 30 minutes.

**Comment by filthyrake** [comment]
you can cause the client to OOM if you pipe too much data to it :D
