### ISSUE TITLE
sensu-client fails to restart when a check is not finished yet and may hang forever in a broken state

### ISSUE THREAD

**Issue by stefanandres** [sensu/sensu#1052]
When sensu-client is running local checks which might take longer (or never end, because of a bug) the sensu-client cannot restart:

Stopping the client fails:

```
root@xxx- /etc/sensu/conf.d/checks(controller-slave) $ /etc/init.d/sensu-client restart
 * Stopping sensu-client                                                                                                                                                        * Timed out waiting for sensu-client to stop
                                                                                                                                                                        [fail]
root@xxx- /etc/sensu/conf.d/checks(controller-slave) $ ps auxw|grep sensu-cl
sensu     5099  0.2  0.0 1440020 27052 ?       Sl   13:31   0:06 /opt/sensu/embedded/bin/ruby /opt/sensu/bin/sensu-client -b -c /etc/sensu/config.json -d /etc/sensu/conf.d -e /etc/sensu/extensions -p /var/run/sensu/sensu-client.pid -l /var/log/sensu/sensu-client.log -L info
```

Killing the sensu-client only works with -9. When doing so, it cannot start properly again:

```
root@xxx- /etc/sensu/conf.d/checks(controller-slave) $ killall -9 sensu-client
sensu-client: no process found
root@xxx- /etc/sensu/conf.d/checks(controller-slave) $ /etc/init.d/sensu-client start
 * Starting sensu-client                           [fail]
```

The log file only says

```
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:859:in `open_udp_socket': no datagram socket (RuntimeError)
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:859:in `open_datagram_socket'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/client/process.rb:355:in `setup_sockets'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/client/process.rb:413:in `start'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/client/process.rb:19:in `block in run'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `call'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/client/process.rb:18:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/bin/sensu-client:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-client:23:in `load'
        from /opt/sensu/bin/sensu-client:23:in `<main>'
```

When adding debug output, it says port already in use for 3030/UDP

```
root@xxx- /etc/sensu/conf.d/checks(controller-slave) $ netstat -ntulp|grep 3030
udp        0      0 127.0.0.1:3030          0.0.0.0:*                           602/sh
root@xxx- /etc/sensu/conf.d/checks(controller-slave) $ kill -9^C
root@xxx- /etc/sensu/conf.d/checks(controller-slave) $ ps auxw|grep 602
sensu      602  0.0  0.0   4448   748 ?        S    13:42   0:00 sh -c sudo /usr/lib/nagios/plugins/check_yyy 3
root@xxx- /etc/sensu/conf.d/checks(controller-slave) $ kill -9 602
root@xxx- /etc/sensu/conf.d/checks(controller-slave) $ netstat -ntulp|grep 3030
udp        0      0 127.0.0.1:3030          0.0.0.0:*                           603/sudo
root@xxx- /etc/sensu/conf.d/checks(controller-slave) $ kill -9 603
root@xxx- /etc/sensu/conf.d/checks(controller-slave) $ netstat -ntulp|grep 3030
root@xxx- /etc/sensu/conf.d/checks(controller-slave) $ /etc/init.d/sensu-client start
 * Starting sensu-client                                                              [ OK ]
root@xxx- /etc/sensu/conf.d/checks(controller-slave) $
```

So killing all childprocesses is the only way. I consider that a bug, I would think it should a) abandon the childs or b) kill the childs c) give a proper log message

**Comment by portertech** [comment]
@stefanandres I would start by using `"timeout": 60` in your check definitions to set a hard stop. We should revisit https://github.com/sensu/sensu-spawn to stop child processes of inheriting fds from the parent (sensu-client).

**Comment by stefanandres** [comment]
Okay, I have like a few hundres checks already in different repos and all (directly using sensu::check) - I'd need this as default to properly work, do you have a workaround for that?

**Comment by stefanandres** [comment]
This is especially game-breaking when you configure a new check via puppet with sensu::check, it restarts the sensu-client, it stops and then fails to start and you'll get keepalive erros on all your clients. :-(

**Comment by stefanandres** [comment]
I've now written a local workaround (deployed via our sensu puppet wrapper ...) which tries to kill all processes via the init script.

```
$ diff -u sensu-service  /tmp/sensu-service
--- sensu-service	2015-09-30 10:49:04.402828677 +0200
+++ /tmp/sensu-service	2015-09-30 10:49:36.598355487 +0200
@@ -237,25 +237,37 @@
 stop() {
     log_daemon_msg "Stopping $sensu_service"

-    set -x
     # try pgrep
     pid=$(pid_pgrep)

-    local pids
-    local count=0
-    # workaround https://github.com/sensu/sensu/issues/1052 for now
-    pids=$(netstat -apn|grep :3030|awk '{print $NF'}|sed 's/\/.*//')
-    while [[ $pids ]]; do
-      kill -9 $pids || true
-      pids=$(netstat -apn|grep :3030|awk '{print $NF'}|sed 's/\/.*//')
-      ((count >= 5)) && break
-      ((count++))
-    done
-
-    if ((count >= 5)); then
-      log_failure_msg "Timed out waiting for $sensu_service to stop"
-      echo_fail
-      return 2
+    if [ ! -n "$pid" ]; then
+        # try the pid file
+        if [ -f "$pidfile" ] ; then
+            read pid < "$pidfile"
+        fi
+    fi
+
+    if [ -n "$pid" ]; then
+        kill $pid
+
+        retval=$?
+
+        if [ $retval -eq 0 ]; then
+            wait_for_stop
+
+            retval=$?
+
+            if [ $retval -eq 0 ]; then
+                echo_ok
+            else
+                log_failure_msg "Timed out waiting for $sensu_service to stop"
+                echo_fail
+            fi
+        else
+            echo_fail
+        fi
+
+        return $retval
     else
       log_action_msg "$sensu_service is stopped"
       return 3
``

**Comment by portertech** [comment]
I suspect that Sensu is spawning child processes (for checks etc.) that are hanging onto fds, like the UDP socket. We need to have a good look at https://github.com/sensu/sensu-spawn/blob/master/lib/sensu/spawn.rb

**Comment by portertech** [comment]
We could potentially improve Sensu's stop signal handling to manage the child process groups.

**Comment by patwakeem** [comment]
pids=$(netstat -apn|grep :3030|awk '{print $NF'}|sed 's/\/.*//') can cause some problems with killing other processes. We recommend filtering a bit more.

**Comment by xyntrix** [comment]
Was this ever fixed?  

Did adding an explicit timeout work as a viable workaround?

**Comment by portertech** [comment]
Sensu >= 0.27 using native service managers, or sysvinit with SERVICE_MAX_WAIT, and using Sensu check `timeout` were applicable is the solution.
