### ISSUE TITLE
sensu-server stopped working 0.20.6

### ISSUE THREAD

**Issue by p1hr** [sensu/sensu#1077]
Hi,
last night my Sensu stopped working, meaning no checks ran.
Current setup is as follows:

Sensu: 0.20.6
Redis: 3.0.5
RabbitMQ: 3.5.6
OS: Debian Jessie

Below is what found in logs:

sensu-api.log

```
{"timestamp":"2015-10-19T19:26:22.857026+0100","level":"warn","message":"reconnecting to redis"}
{"timestamp":"2015-10-19T19:26:23.940690+0100","level":"info","message":"reconnected to redis"}
{"timestamp":"2015-10-19T19:26:24.845831+0100","level":"info","message":"GET /stashes","remote_address":"10.78.196.61","user_agent":"Go-http-client/1.1","request_method":"GET","request_uri":"/stashes","request_body":""}
{"timestamp":"2015-10-19T19:26:24.852303+0100","level":"info","message":"GET /checks","remote_address":"10.78.196.61","user_agent":"Go-http-client/1.1","request_method":"GET","request_uri":"/checks","request_body":""}
{"timestamp":"2015-10-19T19:26:24.854008+0100","level":"info","message":"GET /clients","remote_address":"10.78.196.61","user_agent":"Go-http-client/1.1","request_method":"GET","request_uri":"/clients","request_body":""}
{"timestamp":"2015-10-19T19:26:24.872802+0100","level":"info","message":"GET /events","remote_address":"10.78.196.61","user_agent":"Go-http-client/1.1","request_method":"GET","request_uri":"/events","request_body":""}
{"timestamp":"2015-10-19T19:26:24.933460+0100","level":"info","message":"GET /info","remote_address":"10.78.196.61","user_agent":"Go-http-client/1.1","request_method":"GET","request_uri":"/info","request_body":""}
{"timestamp":"2015-10-19T19:26:24.935427+0100","level":"fatal","message":"transport connection error","error":"rabbitmq channel closed"}
{"timestamp":"2015-10-19T19:26:24.935576+0100","level":"warn","message":"reconnecting to transport"}
```

rabbit@rabbit.log
```
=ERROR REPORT==== 19-Oct-2015::19:26:22 ===
Channel error on connection <0.12707.3> (10.78.196.61:35500 -> 10.78.196.62:5672, vhost: '/sensu', user: 'sensu'), channel 1:
{amqp_error,precondition_failed,"unknown delivery tag 14484",'basic.ack'}

=WARNING REPORT==== 19-Oct-2015::19:26:22 ===
closing AMQP connection <0.12707.3> (10.78.196.61:35500 -> 10.78.196.62:5672):
connection_closed_abruptly

=ERROR REPORT==== 19-Oct-2015::19:26:24 ===
Channel error on connection <0.12728.3> (10.78.196.61:35501 -> 10.78.196.62:5672, vhost: '/sensu', user: 'sensu'), channel 1:
{amqp_error,not_found,"no queue 'keepalives' in vhost '/sensu'",
            'queue.declare'}
```

sensu-server.log
```
{"timestamp":"2015-10-19T19:26:22.857344+0100","level":"warn","message":"reconnecting to redis"}
{"timestamp":"2015-10-19T19:26:22.857554+0100","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2015-10-19T19:26:22.857822+0100","level":"warn","message":"resigning as leader"}
{"timestamp":"2015-10-19T19:26:22.866075+0100","level":"fatal","message":"transport connection error","error":"rabbitmq channel closed"}
{"timestamp":"2015-10-19T19:26:22.866275+0100","level":"warn","message":"reconnecting to transport"}
{"timestamp":"2015-10-19T19:26:23.858878+0100","level":"info","message":"reconnected to redis"}
{"timestamp":"2015-10-19T19:26:23.861681+0100","level":"warn","message":"reconnecting to redis"}
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/session.rb:738:in `send_frame': The connection is closed, you can't use it anymore! (AMQP::ConnectionClosedError)
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/channel.rb:1022:in `acknowledge'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/header.rb:35:in `ack'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-3.2.0/lib/sensu/transport/rabbitmq.rb:74:in `acknowledge'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-3.2.0/lib/sensu/transport/base.rb:117:in `ack'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/process.rb:71:in `block (2 levels) in setup_keepalives'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/process.rb:52:in `call'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/process.rb:52:in `block (2 levels) in update_client_registry'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:489:in `call'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:489:in `dispatch_response'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:443:in `process_cmd'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:408:in `receive_data'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/process.rb:23:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/bin/sensu-server:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-server:23:in `load'
        from /opt/sensu/bin/sensu-server:23:in `<main>'
```

After that I had to restart sensu-server to make it work again.

**Comment by portertech** [comment]
Hi @p1hr, it looks like you are running `sensu-0.20.3`. It is interesting that both AMQP channels were closed, Server and API.

**Comment by p1hr** [comment]
@portertech sorry for the confusion re Sensu version.
Sensu Server is running 0.20.6 , some clients are still running 0.20.3 as I didn't manage to upgrade them all in one go. Could that version difference cause problems?

Just checked gems installed on the Sensu server and there is no gem called sensu-0.20.3, theres sensu-0.20.6 though

**Comment by portertech** [comment]
@p1hr the backtrace that you provided is produced by 0.20.3:

```
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/ ...
```

**Comment by LeonLee88** [comment]
Is this issue open? I got similar issue after I set up more checks on our sensu server. 
```
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/session.rb:738:in `send_frame': The connection is closed, you can't use it anymore! (AMQP::ConnectionClosedError)
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/channel.rb:1022:in `acknowledge'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/header.rb:35:in `ack'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-3.2.0/lib/sensu/transport/rabbitmq.rb:74:in `acknowledge'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-3.2.0/lib/sensu/transport/base.rb:117:in `ack'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/process.rb:71:in `block (2 levels) in setup_keepalives'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/process.rb:52:in `call'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/process.rb:52:in `block (2 levels) in update_client_registry'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:489:in `call'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:489:in `dispatch_response'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:443:in `process_cmd'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:408:in `receive_data'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/process.rb:23:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/bin/sensu-server:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-server:23:in `load'
	from /opt/sensu/bin/sensu-server:23:in `<main>'
```

**Comment by portertech** [comment]
@LeonLee88 a single RabbitMQ or cluster? What does the RabbitMQ log say? Does the log provide additional context?

**Comment by calebhailey** [comment]
Closing due to inactivity. Please feel free to create a new issue if this matter is not resolved.
