### ISSUE TITLE
Sensu 020.6 with RMQ 3.2.1 crash

### ISSUE THREAD

**Issue by kaushiksriram100** [sensu/sensu#1091]
Hi,

Observing this behavior after we upgraded sensu to 0.20.6. 
Sensu Core: 0.20.6 (4 node cluster)
Rabbit MQ (2 node cluster): 3.2.1 (rabbitm.json uses one node on port 5671). Rabbitmq cluster has mirroring. 
Total target clients: 2900
Total checks: 10 (avg) in each client.
Impact: Checks results are taking time to show up and process. 

We see this crashing after 2 hours of running fine. And when 1 sensu server crashes the messages ready in rabbitmq increases to 300K+ (from 2000 or so) and keeps growing (the results queue). After restarting that dead server the count seems to be flat and comes down significantly (after a period of time - around 1 hour)

{"timestamp":"2015-11-06T20:48:06.068389-0800","level":"info","message":"publishing check request","payload":{"name":"agg_keepalive_<redacted>_controller_metric","issued":1446871686,"command":"/etc/sensu/plugins/check_wm_aggregate-region_metric.rb -a 'sensu-api.glb.prod.<redacted>.com' -c 'keepalive' -u <redacted> -p <redacted> -r DFW3 -n CONTROLLER -A openstack -T 1"},"subscribers":["openstack-endpoint-checks"]}
{"timestamp":"2015-11-06T20:48:06.465363-0800","level":"fatal","message":"transport connection error","error":"rabbitmq channel closed"}
{"timestamp":"2015-11-06T20:48:06.465500-0800","level":"warn","message":"reconnecting to transport"}
{"timestamp":"2015-11-06T20:48:06.465570-0800","level":"warn","message":"unsubscribing from keepalive and result queues"}
{"timestamp":"2015-11-06T20:48:06.465678-0800","level":"warn","message":"resigning as leader"}
{"timestamp":"2015-11-06T20:48:06.469269-0800","level":"warn","message":"reconnecting to redis"}
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/session.rb:738:in `send_frame': The connection is closed, you can't use it anymore! (AMQP::ConnectionClosedError)
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:408:in `receive_data'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'

**Comment by kaushiksriram100** [comment]
Also in Rabbitmq logs, for that time frame, I see something like this.. 

=INFO REPORT==== 6-Nov-2015::20:48:06 ===
Synchronising queue 'dal-appblx096-06.prod.walmart.com-0.16.0-1446871686' in vhost '/sensu': all slaves already synced

=INFO REPORT==== 6-Nov-2015::20:48:06 ===
Synchronising queue 'dal-appblx096-06.prod.walmart.com-0.16.0-1446871686' in vhost '/sensu': 0 messages to synchronise

=INFO REPORT==== 6-Nov-2015::20:48:06 ===
Synchronising queue 'dal-appblx096-06.prod.walmart.com-0.16.0-1446871686' in vhost '/sensu': all slaves already synced

=INFO REPORT==== 6-Nov-2015::20:48:06 ===
accepting AMQP connection <0.18952.5706> (10.65.200.162:40808 -> 10.65.200.162:5671)

=ERROR REPORT==== 6-Nov-2015::20:48:06 ===
connection <0.7125.5702>, channel 1 - soft error:
{amqp_error,precondition_failed,"unknown delivery tag 1268060",'basic.ack'}

=WARNING REPORT==== 6-Nov-2015::20:48:06 ===
closing AMQP connection <0.7125.5702> (10.65.72.65:53330 -> 10.65.200.162:5671):
connection_closed_abruptly
=INFO REPORT==== 6-Nov-2015::20:48:06 ===
accepting AMQP connection <0.18962.5706> (10.65.200.163:55370 -> 10.65.200.162:5671)

=INFO REPORT==== 6-Nov-2015::20:48:06 ===
accepting AMQP connection <0.18969.5706> (10.65.200.163:55371 -> 10.65.200.162:5671)

=INFO REPORT==== 6-Nov-2015::20:48:06 ===

**Comment by kaushiksriram100** [comment]
Hardware Specs:

redis:slave
[root@dal-appblx004-11 ~]# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 45
Stepping:              7
CPU MHz:               1200.000
BogoMIPS:              4594.67
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0-7,16-23
NUMA node1 CPU(s):     8-15,24-31

**Comment by kaushiksriram100** [comment]
Could these be because of some connection drops in the network? We never saw these type of issues in older version so unable to comprehend.

**Comment by portertech** [comment]
@kaushiksriram100 what version of Sensu core did you upgrade from?

**Comment by portertech** [comment]
It appears the the AMQP channel errors could be related to your HA RabbitMQ configuration. The Sensu documentation has recently been updated to include HA RabbitMQ configuration https://sensuapp.org/docs/latest/rabbitmq#configuring-rabbitmq-for-high-availability-ha including a RabbitMQ policy to only mirror the "results" and "keepalives" queues https://sensuapp.org/docs/latest/rabbitmq#mirroring-the-sensu-queues (instead of every queue which is unnecessary and taxing).

**Comment by kaushiksriram100** [comment]
We upgraded from 0.16 to 0.20.6

**Comment by kaushiksriram100** [comment]
Thank you Sean,

We didn't make any rabbitmq config changes as a part of sensu upgrade. The
rabbitmq setup is the same was with 0.16.

I will remove the mirroring of other queues (other than results and
keepalives) as you recommend.

The followup to this crash is that other sensu servers are just unable to
handle. The messages keep growing in rabbitmq and it introduces a severe
latency. That is where I was trying to find out what is the ideal setup for
around 3000 clients with around 10 avg checks. We are running 4 bare metal
servers.

**Comment by poolski** [comment]
I'm having this issue with a brand new Sensu environment, all commissioned by Puppet, including Erlang and RMQ - only four hosts and no mirroring as far as I can tell. 

Could this be a RMQ incompatibility with the latest version? I'm running `3.5.6` on an Ubuntu 14.04 box.

**Comment by poolski** [comment]
Update:

I get the same results running rabbitmq 3.2.4:

```
{"timestamp":"2015-11-16T16:50:46.220562+0000","level":"info","message":"determining stale clients"}
{"timestamp":"2015-11-16T16:50:46.220867+0000","level":"info","message":"determining stale check results"}
{"timestamp":"2015-11-16T16:50:46.231883+0000","level":"warn","message":"reconnecting to redis"}
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/process.rb:282:in `>=': comparison of Fixnum with String failed (ArgumentError)
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/process.rb:282:in `check_flapping?'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/process.rb:313:in `block in update_event_registry'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:489:in `call'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:489:in `dispatch_response'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:434:in `process_cmd'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:408:in `receive_data'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/lib/sensu/server/process.rb:23:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.3/bin/sensu-server:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-server:23:in `load'
	from /opt/sensu/bin/sensu-server:23:in `<main>'
```

**Comment by portertech** [comment]
@poolski are you setting check flapping thresholds? The error suggests https://github.com/sensu/sensu/blob/aa35fc637b5eca6a9c8575bf58ba5cfcf06f1f6b/lib/sensu/server/process.rb#L282

**Comment by portertech** [comment]
@poolski Also, 0.20.6 is the latest version :+1:

**Comment by portertech** [comment]
@kaushiksriram100 Are your Sensu server boxes heavily loaded? Have you configured a Sensu RabbitMQ `"prefetech"` value to increase message throughput? (at the cost of even distribution)

**Comment by poolski** [comment]
@portertech I think I am, but I'm also running a cluster of *four* machines right now, so the load is miniscule. 

This is going to sound dumb, but how do I upgrade to the latest version? It's not in the repos as far as I can tell - am I looking at a `gem install --upgrade sensu` rather than a package update?

**Comment by poolski** [comment]
@portertech also, my flap thresholds are set as follows:
```
"elasticsearch-status": {
      "command": "check-es-cluster-status.rb -h %{::ipaddress}",
      "handlers": [
        "default"
      ],
      "high_flap_threshold": "20",
      "interval": 120,
      "low_flap_threshold": "5",
      "refresh": 1209600,
      "standalone": true
    }
```

To be quite honest, I'm not sure what those should be set to but on my other sensu env, these settings produce no errors.

**Comment by portertech** [comment]
@poolski The Sensu repository moved a few weeks back, to work with the new build pipeline: 

https://sensuapp.org/docs/latest/install-repositories#install-the-sensu-core-repository

Those thresholds should be integers! Configuration validation should have stopped Sensu from running, I'll check on this :+1:

**Comment by portertech** [comment]
@poolski oh, and for upgrading https://sensuapp.org/docs/latest/upgrading#upgrading-the-sensu-package

**Comment by kaushiksriram100** [comment]
@portertech, In our env we have 1 flapping threshold check. I checked the load on these servers and they look OK. It's in this range -> OK - load average: 0.90, 0.80, 0.57 

We are not using any prefetch currently. What value do you suggest for prefetch? 

"checks": {
    "mem-swap_hypervisor_3xl_juno_openstack": {
        "handlers": ["Handler1"],
      "command": "check_wm_mem_swap -u -C -w 96.5,50 -c 98,60",
      "interval": 120,
      "flapping": true,
      "low_flap_threshold": 10,
      "high_flap_threshold": 25,
      "subscribers": [ "openstack-hypervisors-3xl-juno" ],
      "team": "test@example.com",
      "runbook": "confluence",
      "dependencies": [ "proc-nova-compute_hypervisor_3xl_juno_openstack" ]
    },

**Comment by portertech** [comment]
@poolski Looks like older versions of Sensu do not properly validate the thresholds. Upgrading will guard against comparison errors.

**Comment by portertech** [comment]
@kaushiksriram100 The low load average suggest that your Sensu servers are more than capable of dealing with the number of messages building in the queue. Please refer to the Sensu RabbitMQ definition reference documentation for "prefetch" https://sensuapp.org/docs/latest/rabbitmq#definition-attributes :+1: This attribute will allow for higher throughput.

**Comment by poolski** [comment]
@portertech It's still happening, even with Sensu 0.20.6. Still getting the same issues. 
Not quite sure what's going on here :(

I tried to upgrade to 0.21.0 but that had zero effect.

**Comment by calebhailey** [comment]
@kaushiksriram100 closing due to inactivity. Please feel free to create a new issue if this matter is not resolved.

@poolski it looks like you were having an issue that ended up being unrelated to the OP's issue - it looks like the error had to do with your flapping configuration parameters being set as strings instead of integers, and older versions of Sensu weren't property validating and detecting that your configuration was invalid. Please open a new issue if you still need help. 

#monitoringlove
