### ISSUE TITLE
sensu-client: IPv6 resolver does not work

### ISSUE THREAD

**Issue by pstadt** [sensu/sensu#1192]
I just configured a sensu-client with rabbitmq ipv6 communication using ssl.

When using the raw IPv6 address for rabbitmq.host everything is fine.
If I use a dnsname with an AAAA record only (no A record for this dnsname) sensu does not start at all:

```
/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:681:in `connect_server': unable to resolve server address: Success (EventMachine::ConnectionError)
        from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:681:in `bind_connect'
        from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:657:in `connect'
        from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/amqp-1.5.0/lib/amqp/session.rb:457:in `connect'
        from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/amqp-1.5.0/lib/amqp.rb:242:in `connect'
        from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-transport-4.0.0/lib/sensu/transport/rabbitmq.rb:186:in `setup_connection'
        from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-transport-4.0.0/lib/sensu/transport/rabbitmq.rb:215:in `connect_with_eligible_options'
        from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-transport-4.0.0/lib/sensu/transport/rabbitmq.rb:18:in `connect'
        from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-transport-4.0.0/lib/sensu/transport.rb:22:in `connect'
        from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-0.22.1/lib/sensu/daemon.rb:187:in `setup_transport'
        from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-0.22.1/lib/sensu/client/process.rb:415:in `start'
        from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-0.22.1/lib/sensu/client/process.rb:19:in `block in run'
        from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `call'
        from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-0.22.1/lib/sensu/client/process.rb:18:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-0.22.1/exe/sensu-client:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-client:23:in `load'
        from /opt/sensu/bin/sensu-client:23:in `<main>'

```

"Resolver Error 'Success'" looks like the AAAA record was resolved but for creating the  connection it is ignored.

I am not sure if this is a problem of sensu itself or caused by one of the included ruby classes, but hopefully you know how to solve this.

**Comment by portertech** [comment]
@pstadt I am curious if this is still the case with the latest Sensu release, 0.23.0-3.

**Comment by pstadt** [comment]
@portertech in 0.23.0-3 the problem disappeared
