### ISSUE TITLE
Starting sensu-client with sensu-server not available

### ISSUE THREAD

**Issue by lukyanov** [sensu/sensu#1270]
## Expected Behavior
It would be useful to be able to start sensu-client when rabbitmq on the server is not yet available. It is handful when doing configuration management with tools like Chef, Puppet, Ansible, etc. I saw your recommendation to use `runit` with your Chef cookbook, but it is not a generic solution. CentOS 7, for example, uses systemd as a default. Using `runit` there would be kind of a 'foreign' solution. Also Chef is not the only one tool of such kind.

## Current Behavior
sensu-client fails on start when rabbitmq host is not available.

## Possible Solution
sensu-client tries to reconnect when the connection to rabbitmq disappears which is appropriate behaviour. I think similar behaviour should be applied when starting the client. The client should not fail when there is no connection to rabbitmq but instead constantly try to establish the connection (as it already does when the connection disappears).

## Context
sensu-server may not be available at the time a client machine is created and provisioned. Having the server up and running before the client machine adds a complexity to the configuration management workflow.

## Your Environment
CentOS 7

**Comment by portertech** [comment]
@lukyanov The latest version of Sensu (0.23.3) will continue to run and attempt to reconnect to RabbitMQ.

```
$ bundle exec ./exe/sensu-client -c spec/config.json -d spec/conf.d
{"timestamp":"2016-05-17T15:54:24.267641-0700","level":"warn","message":"loading config file","file":"spec/config.json"}
{"timestamp":"2016-05-17T15:54:24.267720-0700","level":"warn","message":"loading config files from directory","directory":"spec/conf.d"}
{"timestamp":"2016-05-17T15:54:24.301929-0700","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
{"timestamp":"2016-05-17T15:54:26.304174-0700","level":"error","message":"[amqp] Detected TCP connection failure: Errno::ECONNREFUSED"}
```

**Comment by portertech** [comment]
Please use a recent version of Sensu :+1:

**Comment by lukyanov** [comment]
I'm using this version in fact.
Well, in my case the host defined in rabbitmq.json is not available at all at the moment of starting the client. With this version I still get this error:

```
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:677:in `connect_server': unable to resolve server address: Inappropriate ioctl for device (EventMachine::ConnectionError)
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:677:in `bind_connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:653:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.5.0/lib/amqp/session.rb:457:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.5.0/lib/amqp.rb:242:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-5.0.0/lib/sensu/transport/rabbitmq.rb:188:in `setup_connection'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-5.0.0/lib/sensu/transport/rabbitmq.rb:218:in `connect_with_eligible_options'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-5.0.0/lib/sensu/transport/rabbitmq.rb:20:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-5.0.0/lib/sensu/transport.rb:24:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.23.2/lib/sensu/daemon.rb:210:in `setup_transport'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.23.2/lib/sensu/client/process.rb:379:in `start'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.23.2/lib/sensu/client/process.rb:19:in `block in run'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.23.2/lib/sensu/client/process.rb:18:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.23.2/exe/sensu-client:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-client:22:in `load'
	from /opt/sensu/bin/sensu-client:22:in `<main>'
```
