### ISSUE TITLE
API config documentation

### ISSUE THREAD

**Issue by jaykumar-jnpr** [sensu/sensu#1299]
Sensu API configuration [documentation](https://sensuapp.org/docs/0.23/platforms/sensu-on-ubuntu-debian.html#example-api-configurations) is vague, I remember documentation of an earlier version mentioned the difference between host and bind IP address

As I understand, 

**host** is the endpoint sensu server would connect for API
**bind** is the local interface/IP sensu-api should bind to.

Is the following configuration valid? If API is loadbalanced on a remote server, how do I specify remote port? 

`
{
  "api": {
    "host": "10.0.0.11:45670",
    "bind": "0.0.0.0",
    "port": 4567
  }
}
`

Atleast in one instance, I have seeing some issue with API configuration

[http://pastebin.com/BwgHruUE](http://pastebin.com/BwgHruUE)
[sensu-plugins-sensu/issues/6](https://github.com/sensu-plugins/sensu-plugins-sensu/issues/6)

**Comment by portertech** [comment]
@jaykumar-jnpr most consumers of `host` expect it to be a hostname/IP, not including the port.

**Comment by jaykumar-jnpr** [comment]
Any suggest workaround, or do we have to have default port 4567 for remote API endpoint?

**Comment by portertech** [comment]
@jaykumar-jnpr what do you have that's consuming the API definition?

**Comment by jaykumar-jnpr** [comment]
@portertech , I am facing issue with Sensu deregister handler, it is trying to make connection to following endpoint, which obviously is wrong.

10.0.0.10:45670:4567

`["/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-handler.rb:134:in `block in filter_silenced': Object#timeout is deprecated, use Timeout.timeout instead.\n/opt/sensu/embedded/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect': Failed to open TCP connection to 10.0.0.10:45670:4567 (getaddrinfo: Name or service not known) `

My api config looks like 

`{ "api": { "host": "10.0.0.11:45670", "bind": "0.0.0.0", "port": 4567 } } `


[sensu-plugins-sensu/issues/6](https://github.com/sensu-plugins/sensu-plugins-sensu/issues/6)

**Comment by cwjohnston** [comment]
It seems that sensu-api process and the sensu-plugin handler class both rely on the api configuration scope in ways that seem to confound expectations here. 

I've commented in sensu-plugins/sensu-plugins-sensu#6 with some thoughts about how this might be resolved for @jaykumar-jnpr 's particular case (running API behind load balancer on alternate port).

**Comment by jaykumar-jnpr** [comment]
@cwjohnston, thanks for detailed explanation. Btw, yes I am already running Redis with replication and Sentinel HA

I still see a use case to add host:port to api configuration scope, to avoid any single point of failure.

Even I if am running sensu api/server on the same server, I see a value in servers pointing to a loadbalanced endpoint to avoid failures/unhealthy state in the case sensu-api die or is not functional on one of the servers. LB is doing a L7 health check on the API service.

I guess the question is, what is the impact of  sensu-api going kaput on the server where sensu-server is the leader, is the environment still healthy?  Leader election in sensu-server make the server component resilient, but what about sensu-api?

**Comment by cwjohnston** [comment]
@jaykumar-jnpr on further reflection I think you're right that theres an improvement to be made here.

To my understanding the server interacts with the HTTP API only when executing pipe handlers, particularly those using the [sensu-plugin library](https://github.com/sensu-plugins/sensu-plugin).

If the API is unreachable, a handler may not be able to complete before timing out, or it may log a failure due to being unable to determine if the check is silenced or some other API call (deleting a client in this case). It is also my understanding that Sensu Server does not presently have any way to gauge the availability of the API, and, due to the nature of pipe handlers, handler execution fail.

Although I agree that the current implementation of API configuration doesn't quite fit the bill, I think we can improve this by enhancing sensu-plugin `api_request` method to support iterating over an array of API endpoints described under a configuration scope that won't require changes to the API server itself, e.g. pointing at a single load balancer:

```json
{ "api": { "endpoints": [ { "host": "192.168.10.11", "port": 45670 } ] } }
```

or directly at one or more APIs:

```json
{ 
  "api": {
    "endpoints": [ 
      { 
        "host": "192.168.10.9",
        "port": 4567
      },
      { 
        "host": "192.168.10.10",
        "port": 4567
      }
    ] 
  } 
}
```

Your thoughts?

**Comment by jaykumar-jnpr** [comment]
@cwjohnston, what is the expected behavior when one of the API dies in the Array, do we have any health check logic to ignore dead API endpoint? Or just basic timeout with exponential back-off.

**Comment by cwjohnston** [comment]
@jaykumar-jnpr lets continue discussion of that proposed feature in sensu-plugins/sensu-plugin#122

**Comment by cwjohnston** [comment]
@jaykumar-jnpr I should also point out that I am working on releasing sensu-plugin v1.3.0 which contains support for overriding sensu `api` configuration using the value of the SENSU_API_URL environment variable (see sensu-plugins/sensu-plugin#81). 

Although I think the configuration interdependency between sensu-plugin and sensu-api needs to be resolved, this environment variable approach seems like something you might be able to use more immediately.

**Comment by calebhailey** [comment]
Tagging this for inclusion in the 0.27 release, along with the other API enhancements described in #1220.

**Comment by portertech** [comment]
I think we should add validation to sensu-settings for the following JSON spec proposed by @cwjohnston.

``` json
{ 
  "api": {
    "endpoints": [ 
      { 
        "host": "192.168.10.9",
        "port": 4567
      },
      { 
        "host": "192.168.10.10",
        "port": 4567
      }
    ] 
  } 
}
```

Sensu services will not use the "endpoints" configuration to begin, but may do so in the future. Users can configured their own API endpoints, e.g. AWS ELB host and port.
