### ISSUE TITLE
Sensu Server and API crash on reconnection (only) to Redis when port is a string

### ISSUE THREAD

**Issue by nhooey** [sensu/sensu#1354]
I get this stack trace in `server-api.log`, and all Sensu Server and API instances crash:

```
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:794:in `connect_server': no implicit conversion of String into Integer (TypeError)
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:794:in `reconnect'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/em/connection.rb:686:in `reconnect'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-1.4.0/lib/sensu/redis/client.rb:90:in `block (2 levels) in reconnect!'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-1.4.0/lib/sensu/redis/client.rb:40:in `determine_address'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-1.4.0/lib/sensu/redis/client.rb:89:in `block in reconnect!'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/server/process.rb:31:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/exe/sensu-server:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-server:22:in `load'
        from /opt/sensu/bin/sensu-server:22:in `<main>'
```

And the `sensu-server.log` is completely empty.

The servers work for days and then suddenly crash without changing any settings while it's running.

This happens with Sensu 0.25.3-1 from the Ubuntu Apt repository.

**Comment by nhooey** [comment]
It just happened again. I was able to find that exact stack trace in `sensu-api.log`, but `sensu-server.log` is completely empty. A crash shouldn't truncate the server log, that needs to be fixed independent of the crash.

This is a bug where all Sensu server and API instances crash, completely breaking Sensu.
@portertech, @calebhailey: Could you please look in to this?

I think the crash comes from a reconnection attempt when the Redis port is a string value instead of an integer. The server starts up and works without issue, so it must be converting a string port on connect, but not reconnect.
