### ISSUE TITLE
Sensu server unable to open file in /tmp 

### ISSUE THREAD

**Issue by hemendra619** [sensu/sensu#1381]
```
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings/loader.rb:353:in `initialize': Permission denied @ rb_sysopen - /tmp/sensu_server_loaded_files (Errno::EACCES)
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings/loader.rb:353:in `open'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings/loader.rb:353:in `create_loaded_tempfile!'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings/loader.rb:155:in `set_env!'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings.rb:28:in `load'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings.rb:42:in `get'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.5/lib/sensu/daemon.rb:131:in `load_settings'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.5/lib/sensu/daemon.rb:51:in `initialize'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.5/lib/sensu/server/process.rb:42:in `initialize'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.5/lib/sensu/server/process.rb:30:in `new'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.5/lib/sensu/server/process.rb:30:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.5/exe/sensu-server:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-server:22:in `load'
	from /opt/sensu/bin/sensu-server:22:in `<main>'
```

I am using ubuntu 14.04 and sensu version 

```
ubuntu@monitoring-2:/opt/sensu/bin$ ./sensu-server --version
0.25.5
```

/tmp permissions 

`drwxrwxrwt  4 root root  4096 Jul 20 15:24 tmp`

I have switched user to root and still same error

**Comment by cwjohnston** [comment]
Hi @hemendra619, thanks for opening this issue. Were you able to determine the reason that permission was denied for opening `/tmp/sensu_server_loaded_files` ? Some possible reasons may include file permissions or restrictive security environments (e.g. SELinux) 

We have opened #1319 to evaluate a solution that isn't dependent on /tmp, which may help with similar situations in the future.

**Comment by hemendra619** [comment]
This issue was due to some mess up in https://github.com/sensu/sensu-settings/blob/master/lib/sensu/settings/loader.rb  It worked when the loader got updated to next version.

Thanks for the reply. #1319 seems promising

**Comment by cwjohnston** [comment]
See also: https://github.com/sensu/sensu-settings/issues/21#issuecomment-222059444
