### ISSUE TITLE
panic on windows powershell metric collection

### ISSUE THREAD

**Issue by celevra** [sensu/sensu#1391]
Hi,

at first, thank you for your work, sensu is an amazing product!

i'm on sensu 0.25.5

with this metric collection, i run it through sysnative because i want to run it in 64bit mode, there are executables (like the backup commands) that are only running in the 64bit version:

```
{
  "checks": {
    "metrics_win_cpu": {
      "type": "metric",
      "handlers": ["graphite"],
      "command": "%SystemRoot%\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe -ExecutionPolicy Unrestricted -f /opt/sensu/checks/metric-windows-cpu-load.ps1 -schema stats.:::name:::.cpu",
      "interval": 30,
      "subscribers": [ "winall" ]
    },
    "metrics_win_uptime": {
      "type": "metric",
      "handlers": ["graphite"],
      "command": "%SystemRoot%\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe -ExecutionPolicy Unrestricted -f /opt/sensu/checks/netric-windows-uptime.ps1 -schema stats.:::name:::.uptime",
      "interval": 30,
      "subscribers": [ "winall" ]
    }
  }
}
```

i get this error:

```
{"timestamp":"2016-07-27T23:11:40.599938+0200","level":"info","message":"publishing check request","payload":{"type":"metric","handlers":["graphite"],"command":"%SystemRoot%\\sysnative\\WindowsPowerShell\\v1.0\\powershell.exe -ExecutionPolicy Unrestricted -f /opt/sensu/checks/netric-windows-uptime.ps1 -schema stats.:::name:::.uptime","name":"metrics_win_uptime","issued":1469653900},"subscribers":["winall"]}
{"timestamp":"2016-07-27T23:11:40.705212+0200","level":"warn","message":"reconnecting to redis"}
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.5/lib/sensu/server/process.rb:311:in `split': invalid byte sequence in UTF-8 (ArgumentError)
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.5/lib/sensu/server/process.rb:311:in `truncate_check_output'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.5/lib/sensu/server/process.rb:337:in `store_check_result'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.5/lib/sensu/server/process.rb:583:in `block in process_check_result'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.5/lib/sensu/server/process.rb:547:in `block in retrieve_client'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-1.4.0/lib/sensu/redis/client.rb:315:in `dispatch_response'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-1.4.0/lib/sensu/redis/client.rb:337:in `parse_response_line'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-redis-1.4.0/lib/sensu/redis/client.rb:365:in `receive_data'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.5/lib/sensu/server/process.rb:31:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.5/exe/sensu-server:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-server:22:in `load'
        from /opt/sensu/bin/sensu-server:22:in `<main>'
```

this is content of the check:

```
Param (
    [string]$schema = "stats."+(hostname).ToLower()+".uptime"
 )

$ThisProcess = Get-Process -Id $pid
$ThisProcess.PriorityClass = "BelowNormal"

$Counter = ((Get-Counter "\System\System Up Time").CounterSamples)

$Path = ($Counter.Path).Trim("\\") -replace " ","_" -replace "\\","." -replace "[\{\}]","" -replace "[\[\]]",""
$Value = [System.Math]::Truncate($Counter.CookedValue)
$Time = [int][double]::Parse((Get-Date -UFormat %s))

Write-Host "$schema $Value $Time"
```

this is the output if i run it manually:

```
PS C:\opt\sensu\checks> .\metric-windows-uptime.ps1 -schema stats.dgvt-ts02.uptime
stats.dgvt-ts02.uptime6287 1469660820
PS C:\opt\sensu\checks>
```

is there anything else i can provide to dig deeper?

regards

**Comment by portertech** [comment]
Closing due to inactivity. Please feel free to create a new issue if this matter is not resolved.

Sorry for not getting to this 😞
