### ISSUE TITLE
Upgrade from 0.25.5 to 0.26.1 fails for server and api

### ISSUE THREAD

**Issue by UnitedMarsupials** [sensu/sensu#1444]
I did `gem update` to get the latest versions of all of the installed gems on the system. This included updating Sensu and some of the gems it uses. After the upgrade, `sensu-client` restarted nicely, but both `sensu-server` and `sensu-api` are failing:

    /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/sensu-settings-9.1.1/lib/sensu/settings/loader.rb:313:in `load_client_env': undefined method `[]=' for nil:NilClass (NoMethodError)
            from /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/sensu-settings-9.1.1/lib/sensu/settings/loader.rb:115:in `load_env'
            from /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/sensu-settings-9.1.1/lib/sensu/settings.rb:15:in `load'
            from /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/sensu-settings-9.1.1/lib/sensu/settings.rb:43:in `get'
            from /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/sensu-0.26.1/lib/sensu/daemon.rb:133:in `load_settings'
            from /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/sensu-0.26.1/lib/sensu/daemon.rb:53:in `initialize'
            from /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/sensu-0.26.1/lib/sensu/server/process.rb:42:in `initialize'
            from /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/sensu-0.26.1/lib/sensu/server/process.rb:30:in `new'
            from /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/sensu-0.26.1/lib/sensu/server/process.rb:30:in `run'
            from /opt/rh/rh-ruby22/root/usr/local/share/gems/gems/sensu-0.26.1/exe/sensu-server:10:in `<top (required)>'
            from /opt/rh/rh-ruby22/root/usr/local/bin/sensu-server:23:in `load'
            from /opt/rh/rh-ruby22/root/usr/local/bin/sensu-server:23:in `<main>'

My config-files haven't changed -- is there some setting I'm missing, that is now mandatory?

**Comment by UnitedMarsupials** [comment]
Looking at the offending line, I see the `SENSU_CLIENT_SUBSCRIPTIONS` environment variable being access unconditionally -- unlike the other such variables before it. Should the line read:

```diff
         @settings[:client][:address] = ENV["SENSU_CLIENT_ADDRESS"] if ENV["SENSU_CLIENT_ADDRESS"]
-        @settings[:client][:subscriptions] = ENV.fetch("SENSU_CLIENT_SUBSCRIPTIONS", "").split(",")
+        @settings[:client][:subscriptions] = ENV.fetch("SENSU_CLIENT_SUBSCRIPTIONS", "").split(",") if ENV["SENSU_CLIENT_ADDRESS"]
```
Or is this particular variable always supposed to be set?
