### ISSUE TITLE
Custom JSON sent to AMQP queue crashes sensu-server

### ISSUE THREAD

**Issue by jaxxstorm** [sensu/sensu#1496]
If you want to send ad-hoc manual JSON down a AMQP broker, you can crash the sensu-server process pretty easily by omitting certain fields. This seems like a reasonably easy way to interrupt or annoy a company.

## Expected Behavior
The sensu server doesn't crash if the JSON isn't in a valid format.

## Current Behavior
If you send the following JSON directly to an AMQP queue:

```
{"name":"testing","command":"/bin/echo hello","status":0,"output":"hello\n","source":"wrapper_test"}
```

Without the client section, all sensu servers will crash with the following error:

```
{"timestamp":"2016-11-18T16:23:56.221292+0000","level":"warn","message":"reconnecting to redis"}
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/server/process.rb:532:in `retrieve_client': undefined method `[]' for nil:NilClass (NoMethodError)
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/server/process.rb:573:in `process_check_result'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/server/process.rb:609:in `block in setup_results'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/consumer.rb:162:in `block in on_delivery'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/callbacks.rb:37:in `block in exec_callback'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/callbacks.rb:37:in `each'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/callbacks.rb:37:in `exec_callback'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/consumer.rb:294:in `handle_delivery'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/consumer.rb:348:in `block in <class:Consumer>'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:959:in `receive_frameset'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:933:in `receive_frame'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:671:in `receive_data'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/server/process.rb:31:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/exe/sensu-server:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-server:22:in `load'
	from /opt/sensu/bin/sensu-server:22:in `<main>'
```

## Possible Solution
Better checking of JSON on lib/sensu/server/process.rb:532

## Your Environment

* Sensu version used: 0.25-3
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7

**Comment by portertech** [comment]
@jaxxstorm Sensu trusts its transport to be private/controlled. If Sensu were to test for the existence of certain fields (attributes), it would also need to validate the data they contain or risk corrupting state which could introduce a persistent issue (continue to crash, unable to load data etc).

**Comment by portertech** [comment]
I chose not walk down the road of mistrust, as only taking a few steps is worse, imo.

**Comment by jaxxstorm** [comment]
I trust your judgement
