### ISSUE TITLE
Sensu Spits out stack trace of Ruby gems instead of logging what the error is

### ISSUE THREAD

**Issue by DRrawlins** [sensu/sensu#1529]
In sensu 0.26.5-2 for when making a client.json, certain expected arrays will throw ruby stack trace rather than tell you its an issue with the file.

## Expected Behavior

```
"timestamp":"2017-01-13T15:51:41.522272+0000","level":"fatal","message":"config file must be valid json","file":"/etc/sensu/conf.d/client.json","error":"unexpected character at line 9, column 18 [parse.c:652]"}
```
**When handlers are not an array**
```
{"timestamp":"2017-01-13T15:53:21.636106+0000","level":"fatal","message":"client subscriptions must be an array","object":{"name":"vagrant","address":"localhost","subscriptions":"default","os":"Placeholder","osrelease":"Placeholder","safe_mode":false,"handlers":["default"],"keepalive":{"thresholds":{"handlers":["default"],"warning":40,"critical":60}}}}
```
**When subscriptions are not an array**

## Current Behavior
```
{"timestamp":"2017-01-13T15:53:21.636131+0000","level":"fatal","message":"SENSU NOT RUNNING!"}
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-9.2.1/lib/sensu/settings/loader.rb:180:in `load_client_overrides': undefined method `uniq!' for "defaultclient:vagrant":String (NoMethodError)
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-9.2.1/lib/sensu/settings/loader.rb:187:in `load_overrides!'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-9.2.1/lib/sensu/settings.rb:32:in `load'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-9.2.1/lib/sensu/settings.rb:48:in `get'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/daemon.rb:133:in `load_settings'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/daemon.rb:53:in `initialize'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/client/process.rb:29:in `initialize'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/client/process.rb:17:in `new'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/client/process.rb:17:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/exe/sensu-client:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-client:22:in `load'
        from /opt/sensu/bin/sensu-client:22:in `<main>'
```
**When subscriptions are not an array**
```
{"timestamp":"2017-01-13T15:56:45.420419+0000","level":"fatal","message":"config file must be valid json","file":"/etc/sensu/conf.d/client.json","error":"unexpected character at line 9, column 18 [parse.c:652]"}
{"timestamp":"2017-01-13T15:56:45.420439+0000","level":"fatal","message":"SENSU NOT RUNNING!"}
```
**when handlers are not an array**

**Comment by msteggink** [comment]
You can validate your json with jq or jsonlint before applying.

**Comment by DRrawlins** [comment]
You can do lots of things, but it's still valid JSON, so that would not help at all. If sensu is expecting an array instead of a list it should tell you in its logs, that is doing so. Linting the file will merely tell you that is valid, and then still fail.

**Comment by portertech** [comment]
It looks like were are doing some things with the client definition prior to running the settings validators.

The failures is coming from https://github.com/sensu/sensu-settings/blob/master/lib/sensu/settings/loader.rb#L177 as the client subscriptions are not an array. We are going to add a `is_a?(Array)` conditional to guard against this.

We are going to address these issues one at a time.

**Comment by baweaver** [comment]
@portertech: It'd be easier to do this:

```ruby
[1] pry(main)> Array(1)                                                                                                
=> [1]
[2] pry(main)> Array([1])
=> [1]
[3] pry(main)> Array(nil).compact
=> []
```

...which would make the code:

```ruby
def load_client_overrides
  @settings[:client][:subscriptions] =
    Array(@settings[:client][:subscriptions])
      .concat("client:#{@settings[:client][:name]}")
      .compact
      .uniq
      
  warning("applied sensu client overrides", :client => @settings[:client])
end
```

**Comment by portertech** [comment]
@baweaver we could, but it's probably best to allow the invalid subscriptions to pass through unmodified to the validators, in order to alert the user to the bad configuration.
