### ISSUE TITLE
Sensu Client dies with uninitialized constant

### ISSUE THREAD

**Issue by ChrisOnToure** [sensu/sensu#1557]
CentOS 7.2.1511
sensu-client v0.25.3

Sensu Client dies with the following message in the log, after a client restart everything is back fine:

> {"timestamp":"2017-02-15T09:17:13.001755+0700","level":"warn","message":"reconnecting to transport"}
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/framing/string/frame.rb:29:in `decode': uninitialized constant AMQP::Framing::String::Frame::NoFinalOctetError (NameError)
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:671:in `receive_data'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/client/process.rb:18:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/exe/sensu-client:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-client:22:in `load'
        from /opt/sensu/bin/sensu-client:22:in `<main>'

**Comment by portertech** [comment]
@ChrisOnToure is this only happening on a single machine? We think it could be related to either a bad network interface or system memory.

**Comment by portertech** [comment]
Closing due to inactivity.
