### ISSUE TITLE
Sensu Client dies with to_sym undefined method / invalid encoding symbol

### ISSUE THREAD

**Issue by ChrisOnToure** [sensu/sensu#1559]
CentOS 6.6
sensu-client v0.26.5

Might be related to: #1357

Sensu Client dies with the following message in the log, after a client restart everything is back fine:

`/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings/loader.rb:184:in `definition_exists?': undefined method `to_sym' for nil:NilClass (NoMethodError)
Did you mean?  to_s
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-5.2.0/lib/sensu/settings/loader.rb:62:in `block (2 levels) in create_category_methods'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/client/process.rb:211:in `process_check_request'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/client/process.rb:273:in `block (2 levels) in setup_subscriptions'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/consumer.rb:162:in `block in on_delivery'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/callbacks.rb:37:in `block in exec_callback'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/callbacks.rb:37:in `each'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/callbacks.rb:37:in `exec_callback'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/consumer.rb:294:in `handle_delivery'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/consumer.rb:348:in `block in <class:Consumer>'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:959:in `receive_frameset'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:933:in `receive_frame'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:671:in `receive_data'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/lib/sensu/client/process.rb:18:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.3/exe/sensu-client:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-client:22:in `load'
        from /opt/sensu/bin/sensu-client:22:in `<main>'`

`opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-9.2.1/lib/sensu/settings/loader.rb:227:in `to_sym': invalid encoding symbol (EncodingError)
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-9.2.1/lib/sensu/settings/loader.rb:227:in `definition_exists?'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-9.2.1/lib/sensu/settings/loader.rb:83:in `block (2 levels) in create_category_methods'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/client/process.rb:221:in `process_check_request'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/client/process.rb:283:in `block (2 levels) in setup_subscriptions'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/consumer.rb:162:in `block in on_delivery'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/callbacks.rb:37:in `block in exec_callback'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/callbacks.rb:37:in `each'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/callbacks.rb:37:in `exec_callback'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/consumer.rb:294:in `handle_delivery'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/consumer.rb:348:in `block in <class:Consumer>'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:959:in `receive_frameset'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:933:in `receive_frame'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/amqp-1.6.0/lib/amqp/session.rb:671:in `receive_data'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/lib/sensu/client/process.rb:18:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.26.5/exe/sensu-client:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-client:22:in `load'
        from /opt/sensu/bin/sensu-client:22:in `<main>'`

**Comment by cwjohnston** [comment]
Hi @ChrisOnToure, thanks for opening this issue. 

My interpretation is that your check configuration does not conform to what Sensu expects, as it seems that `definition_exists?` expects a "name" argument (should be the name of the check request the client is attempting to process) which is coming through as `nil`.

Can you please share the configuration that's generating checks for this client? You can use the `--print_config` flag, added in Sensu 0.26, to print the merged configuration, e.g.:

```
sudo -u sensu /opt/sensu/bin/sensu-server -c /etc/sensu/config.json -d /etc/sensu/conf.d --print_config
```

Once you have printed the merged configuration I suggest comparing it your on-disk JSON, as I suspect there may be some character encoding issues involved here.

**Comment by portertech** [comment]
I wonder if a transport handler is configured to send data to an AMQP exchange used by a client subscription.

**Comment by portertech** [comment]
@ChrisOnToure what version of RabbitMQ are you using? https://github.com/sensu/sensu/issues/1558 also has me scratching me head.

**Comment by ChrisOnToure** [comment]
Hi sorry for let you wait, the weekend hit :)

@cwjohnston As checked in the client logs I actually can see wired encoding issues right before the error message appears. The name should be **dfapi-city-search-response-time-localhost**. I checked on our three sensu servers in the check definition the name is correct, I am not sure where this comes from.

`{"timestamp":"2017-02-15T14:20:39.184085+0700","level":"info","message":"received check request","check":{"name":"dfapi-city-seArch-beóponse-time-localhost","issued":1487143239,"command":"/etc/sensu/plugins/df/check-df-api-city-search.rb -u http://localhost/ -b /etc/sensu/plugins/df/df-api-city-search-query.json -t 800"}}
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-9.2.1/lib/sensu/settings/loader.rb:227:in `to_sym': invalid encoding symbol (EncodingError)
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-settings-9.2.1/lib/sensu/settings/loader.rb:227:in `definition_exists?'`

@portertech We have three sensu servers with Rabbitmq replication. Version is: **rabbitmq-server.noarch        3.3.4-1**

**Comment by portertech** [comment]
@ChrisOnToure is this happening on one or more Sensu clients? What is the locale set to on the systems?

**Comment by portertech** [comment]
Closing due to inactivity.
