### ISSUE TITLE
Recurring crashes on 1.1.0

### ISSUE THREAD

**Issue by peterhoeg** [sensu/sensu#1762]
We're seeing this approximately every 3 minutes:

```
Oct 10 15:09:56 app3 sensu-server[1973]: {"timestamp":"2017-10-10T15:09:56.083833+0800","level":"warn","message":"reconnecting to redis"}                   Oct 10 15:09:56 app3 sensu-server[1973]: /nix/store/acmqnmpzs3g3x1nmv1j4f4fzfc49nsj3-sensu-1.1.0/lib/ruby/gems/2.3.0/gems/sensu-1.1.0/lib/sensu/server/proce
ss.rb:1187:in `block (2 levels) in create_check_ttl_results': undefined local variable or method `result_key' for #<Sensu::Server::Process:0x00000002de0588> (NameError)                                                                  
Oct 10 15:09:56 app3 sensu-server[1973]:         from /nix/store/acmqnmpzs3g3x1nmv1j4f4fzfc49nsj3-sensu-1.1.0/lib/ruby/gems/2.3.0/gems/sensu-1.1.0/lib/sensu/server/process.rb:1169:in `each'                                             
Oct 10 15:09:56 app3 sensu-server[1973]:         from /nix/store/acmqnmpzs3g3x1nmv1j4f4fzfc49nsj3-sensu-1.1.0/lib/ruby/gems/2.3.0/gems/sensu-1.1.0/lib/sensu/server/process.rb:1169:in `each_with_index'                                  
Oct 10 15:09:56 app3 sensu-server[1973]:         from /nix/store/acmqnmpzs3g3x1nmv1j4f4fzfc49nsj3-sensu-1.1.0/lib/ruby/gems/2.3.0/gems/sensu-1.1.0/lib/sensu/server/process.rb:1169:in `block in create_check_ttl_results'                
Oct 10 15:09:56 app3 sensu-server[1973]:         from /nix/store/acmqnmpzs3g3x1nmv1j4f4fzfc49nsj3-sensu-1.1.0/lib/ruby/gems/2.3.0/gems/sensu-redis-2.2.0/lib
/sensu/redis/client.rb:337:in `dispatch_response'                             
Oct 10 15:09:56 app3 sensu-server[1973]:         from /nix/store/acmqnmpzs3g3x1nmv1j4f4fzfc49nsj3-sensu-1.1.0/lib/ruby/gems/2.3.0/gems/sensu-redis-2.2.0/lib
/sensu/redis/client.rb:359:in `parse_response_line'
Oct 10 15:09:56 app3 sensu-server[1973]:         from /nix/store/acmqnmpzs3g3x1nmv1j4f4fzfc49nsj3-sensu-1.1.0/lib/ruby/gems/2.3.0/gems/sensu-redis-2.2.0/lib
/sensu/redis/client.rb:387:in `receive_data'
Oct 10 15:09:56 app3 sensu-server[1973]:         from /nix/store/acmqnmpzs3g3x1nmv1j4f4fzfc49nsj3-sensu-1.1.0/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.5/li
b/eventmachine.rb:194:in `run_machine'
Oct 10 15:09:56 app3 sensu-server[1973]:         from /nix/store/acmqnmpzs3g3x1nmv1j4f4fzfc49nsj3-sensu-1.1.0/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.5/li
b/eventmachine.rb:194:in `run'
Oct 10 15:09:56 app3 sensu-server[1973]:         from /nix/store/acmqnmpzs3g3x1nmv1j4f4fzfc49nsj3-sensu-1.1.0/lib/ruby/gems/2.3.0/gems/sensu-1.1.0/lib/sensu
/server/process.rb:33:in `run'
Oct 10 15:09:56 app3 sensu-server[1973]:         from /nix/store/acmqnmpzs3g3x1nmv1j4f4fzfc49nsj3-sensu-1.1.0/lib/ruby/gems/2.3.0/gems/sensu-1.1.0/exe/sensu
-server:10:in `<top (required)>'
Oct 10 15:09:56 app3 sensu-server[1973]:         from /nix/store/acmqnmpzs3g3x1nmv1j4f4fzfc49nsj3-sensu-1.1.0/bin/sensu-server:18:in `load'
Oct 10 15:09:56 app3 sensu-server[1973]:         from /nix/store/acmqnmpzs3g3x1nmv1j4f4fzfc49nsj3-sensu-1.1.0/bin/sensu-server:18:in `<main>'
```

## Your Environment
* Sensu version used: 1.1.0
* Active Sensu extensions (e.g. WizardVan 0.1.0):
```
gem 'history' # needed by extensions-influxdb

# integration
gem 'sensu-plugins-mailer'
gem 'sensu-plugins-pushover'

# extensions
gem 'sensu-extensions-check-dependencies'
# sensu-extensions-influxdb on rubygems.org is not the officially sanctioned extension
gem 'sensu-extensions-influxdb', github: 'sensu-extensions/sensu-extensions-influxdb2', ref: 'c6ccfbd12fd878d4a30096444d8a022aac433252'
gem 'sensu-extensions-snmp-trap'
gem 'sensu-extensions-system-profile'

gem 'sensu-plugins-cgroups'
gem 'sensu-plugins-disk-checks'
gem 'sensu-plugins-http'
gem 'sensu-plugins-influxdb' # checks for influxdb, we do not care about the extension
gem 'sensu-plugins-ipmi'
gem 'sensu-plugins-load-checks'
gem 'sensu-plugins-logs'
gem 'sensu-plugins-network-checks'
gem 'sensu-plugins-raid-checks', github: 'sensu-plugins/sensu-plugins-raid-checks', ref: '5b13a690f317c96c8b44f90af767de2842adfae4'
gem 'sensu-plugins-rabbitmq'
gem 'sensu-plugins-redis'
gem 'sensu-plugins-sensu'
gem 'sensu-plugins-snmp'
gem 'sensu-plugins-systemd'
gem 'sensu-plugins-uptime-checks'
```
* Operating System and version (e.g. Ubuntu 14.04): NixOS 17.09
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): RabbitMQ 3.6.2 on Erlang 19.3

**Comment by peterhoeg** [comment]
Looking at the source, this makes sense as ```result_key``` simply isn't set:

```ruby
@redis.srem("ttl", result_key)
```

**Comment by portertech** [comment]
@peterhoeg I will submit a fix and get a patch build in the pipeline 👍

**Comment by peterhoeg** [comment]
Thanks for the quick turnaround.

**Comment by portertech** [comment]
@peterhoeg you're welcome! Thank you for reporting 👍
