### ISSUE TITLE
Sensu-client - DNS lookups of RabbitMQ endpoint don't backoff or pause when the endpoint is unreachable

### ISSUE THREAD

**Issue by madAndroid** [sensu/sensu#1798]
When the RabbitMQ endpoint for Sensu is unavailable, _and_ that endpoint no longer resolves in DNS, the sensu-client daemon will hammer DNS continuously to resolve the hostname. This effectively causes a DOS of the DNS endpoint. We've seen this in environments that are using Consul endpoints for DNS: when the consul cluster goes away, the sensu-client then hammers DNS until Consul get's restarted and the hostname can be resolved again.

## Expected Behavior

DNS lookups have a exponential backoff, to ensure no excessive lookups take place when the sensu RabbitMQ endpoint is unavailable, and it can't be resolved in DNS. This appears to be the behaviour when the service is started up, but not when it's running.

## Current Behavior

When the RabbitMQ endpoint is unavailable, _and_ the hostname used for the endpoint no longer resolves, the sensu-client floods the DNS server with lookup requests:
```
{"timestamp":"2017-12-15T10:14:31.730992+0000","level":"warn","message":"transport connection error","reason":"tcp connection lost"}
{"timestamp":"2017-12-15T10:14:31.731058+0000","level":"warn","message":"reconnecting to transport"}
{"timestamp":"2017-12-15T10:14:33.754360+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:36.774097+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:37.753484+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:39.792706+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:40.775976+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:42.812358+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:43.752977+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:43.790509+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:45.827538+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:46.773802+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:46.805032+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:48.844940+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:49.789421+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:49.821174+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:51.773628+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:51.878980+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:52.837639+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:52.853165+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:54.807133+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:54.917387+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:55.856304+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:55.871189+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:57.832993+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:57.945842+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:58.880559+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T10:14:58.896073+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
```

## Possible Solution

Implement the same backoff process that's currently in place for when the daemon starts up:
```
{"timestamp":"2017-12-15T09:04:33.198368+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T09:04:36.216298+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T09:04:39.231439+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T09:04:42.251168+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T09:04:45.269033+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T09:04:48.304446+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T09:04:51.323283+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
{"timestamp":"2017-12-15T09:04:54.374572+0000","level":"error","message":"transport connection error","reason":"unable to resolve hostname","host":"foo.service.infradev.consul","error":"getaddrinfo: Name or service not known"}
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-7.0.2/lib/sensu/transport/rabbitmq.rb:40:in `connected?': undefined method `connected?' for nil:NilClass (NoMethodError)
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-transport-7.0.2/lib/sensu/transport/rabbitmq.rb:262:in `block in periodically_reconnect'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.1/lib/eventmachine.rb:194:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.1/lib/eventmachine.rb:194:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.27.0/lib/sensu/client/process.rb:19:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.27.0/exe/sensu-client:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-client:22:in `load'
        from /opt/sensu/bin/sensu-client:22:in `<main>'
```

## Steps to Reproduce (for bugs)
1. Configure a temporary DNS hostname for the RabbitMQ endpoint (Consul has a DNS endpoint which we used to reproduce the issue)
2. Configure Sensu to use this RabbitMQ endpoint, and start the sensu-client process
3. Remove the temporary DNS hostname for RabbitMQ 
4. Block port `5672` on the RabbitMQ server, to simulate the server going down (we used iptables for this)
5. View the sensu-client logs to see the DNS lookups of the temporary DNS hostname failing, and that the daemon doesn't backoff at any point

## Context

Using Consul to provide a DNS endpoint is desirable in cloud or other dynamic environments; however, this can just as easily happen in situations where the RabbitMQ endpoint's IP and hostname change.

## Your Environment

* Sensu version used: `0.27.0`
```
# rpm -qa | grep sensu
sensu-0.27.0-2.el7.x86_64
```
* Active Sensu extensions: various community plugins
* Operating System and version: CentOS7
* Transport and runtime versions: `rabbitmq-server-3.6.5`, `erlang-20.1.1-1`

**Comment by madAndroid** [comment]
In addition to the above, it's important to note that the DNS requests we're seeing appear to ramp up linearly .. the longer the process is up, the more requests are made to the DNS server:

![screen shot 2017-12-13 at 16 54 22](https://user-images.githubusercontent.com/1321437/34039848-e24958da-e199-11e7-9c42-a5f4eeaa019e.png)

**Comment by cwjohnston** [comment]
@madAndroid thanks for your detailed reporting on this! Sorry for the disruption. We can see how the current implementation might be causing this behavior and we'll look into it.

**Comment by cyraxjoe** [comment]
@cwjohnston could you expand a bit more on what do you think is happening? I've just experienced the same situation (fortunately on an alpha env). Is a combination of EM and the `connected?` method error?

**Comment by cwjohnston** [comment]
@cyraxjoe I think you're on the right track. More specifically, I think its related to EventMachine betraying our expectation that retrying `Sensu::Transport::RabbitMQ#resolve_hostname` method will be rate-limited by the logic in `Sensu::Transport::RabbitMQ#periodically_reconnect`.
