### ISSUE TITLE
AIX Client with RabbitMQ SSL fails

### ISSUE THREAD

**Issue by adammcdonagh** [sensu/sensu#1839]
When starting the sensu-client on an AIX 7.1 server, and using RabbitMQ as the transport over SSL, the connection fails.

## Expected Behavior
- Sensu agent should start up fully and successfully establish a connection to RabbitMQ

## Current Behavior
- Sensu agent starts
- Sensu agent attempts to communicate with RabbitMQ over SSL
- Agent generates the error below, and immediately exits

```
/opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5/lib/em/pure_ruby.rb:330:in `initialize': SSL_CTX_use_PrivateKey: key values mismatch (OpenSSL::SSL::SSLError)
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5/lib/em/pure_ruby.rb:330:in `new'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5/lib/em/pure_ruby.rb:330:in `start_tls'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5/lib/em/connection.rb:459:in `start_tls'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/amqp-1.6.0/lib/amqp/session.rb:1180:in `upgrade_to_tls_if_necessary'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/amqp-1.6.0/lib/amqp/session.rb:583:in `post_init'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5/lib/em/connection.rb:58:in `block in new'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5/lib/em/connection.rb:49:in `instance_eval'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5/lib/em/connection.rb:49:in `new'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:683:in `bind_connect'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/eventmachine-1.2.5/lib/eventmachine.rb:653:in `connect'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/amqp-1.6.0/lib/amqp/session.rb:457:in `connect'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/amqp-1.6.0/lib/amqp.rb:242:in `connect'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-transport-7.0.2/lib/sensu/transport/rabbitmq.rb:214:in `setup_connection'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-transport-7.0.2/lib/sensu/transport/rabbitmq.rb:254:in `block in connect_with_eligible_options'
        from /opt/sensu/embedded/lib/ruby/gems/2.4.0/gems/sensu-transport-7.0.2/lib/sensu/transport/rabbitmq.rb:197:in `block in next_connection_options'
```

## Steps to Reproduce (for bugs)
- Install Sensu agent
- Configure to point at RabbitMQ. I even found that it'd generate the same error if you point it at a random HTTPS webserver, since it seems to be the SSL negotiation that's actually failing.
- If using RabbitMQ, I have mine to not require client certs, and not bother to verify clients.
- Start Sensu agent

## Context
Completely unable to use Sensu agents on AIX unless we turn off SSL for RabbitMQ (which isn't ideal). However turning off SSL on RabbitMQ does allow the client to work.

## Your Environment
- Using sensu-1.2.0-1 client
- Running on AIX 7.1

**Comment by amdprophet** [comment]
If both are using port 5671 I'm not sure why the RHEL servers would be working without the private key. Our documentation shows that the `private_key_file` field is required https://docs.sensu.io/sensu-core/1.2/reference/rabbitmq/#ssl-attributes.

**Comment by adammcdonagh** [comment]
Fair enough. It is strange, but I can deal with that if it means it'll all work 😄 Thanks for your help

**Comment by amdprophet** [comment]
No problem, glad I could assist you!
