### ISSUE TITLE
docker sensu stops after few hours

### ISSUE THREAD

**Issue by cwartel** [sensu/sensu#1958]
I can launch and use a docker sensu server. Everything's ok with clients and checks but after a few hours (say 10 or so) it stops

## Expected Behavior
It should run till I stop it

## Current Behavior
It stops unexpectedly

## Possible Solution
Not a clue

## Steps to Reproduce (for bugs)
1. I'm on a google hosted Ubuntu 18.04.1 LTS, using a sudoer user sodoing all docker commands 
```
sudo docker run -v /var/lib/sensu:/var/lib/sensu \
-d --name sensu-backend \
-p 3000:3000 -p 8080:8080 -p 8081:8081 sensu/sensu:latest \
sensu-backend start --state-dir /var/lib/sensu/sensu-backend --log-level debug
```

## Context
Here are its last words when `sudo docker logs -f sensu-backend`

```
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe60179]
> 
> goroutine 198 [running]:
> github.com/sensu/sensu-enterprise-go/backend/store/provider.(*Watcher).Disable(0xc003725080)
>         /Users/splourde/go/src/github.com/sensu/sensu-enterprise-go/backend/store/provider/watcher.go:144 +0xb9
> github.com/sensu/sensu-enterprise-go/backend/licensing.applyFeatureList(0xc0001aae10, 0xc002eddcd0, 0x0, 0x0)
>         /Users/splourde/go/src/github.com/sensu/sensu-enterprise-go/backend/licensing/licensing.go:265 +0xdd
> github.com/sensu/sensu-enterprise-go/backend/licensing.(*Enforcer).disableFeatures(0xc00370e800)
>         /Users/splourde/go/src/github.com/sensu/sensu-enterprise-go/backend/licensing/licensing.go:212 +0x91
> github.com/sensu/sensu-enterprise-go/backend/licensing.(*Enforcer).handleWarning(0xc00370e800, 0x0, 0xe7791f700, 0x267da80)
>         /Users/splourde/go/src/github.com/sensu/sensu-enterprise-go/backend/licensing/licensing.go:245 +0x2f6
> github.com/sensu/sensu-enterprise-go/backend/licensing.(*Enforcer).handleResults(0xc00370e800, 0x45cd01)
>         /Users/splourde/go/src/github.com/sensu/sensu-enterprise-go/backend/licensing/licensing.go:140 +0x475
> github.com/sensu/sensu-enterprise-go/backend/licensing.(*Enforcer).Start.func1(0xc00370e800)
>         /Users/splourde/go/src/github.com/sensu/sensu-enterprise-go/backend/licensing/licensing.go:126 +0x2f
> created by github.com/sensu/sensu-enterprise-go/backend/licensing.(*Enforcer).Start
>         /Users/splourde/go/src/github.com/sensu/sensu-enterprise-go/backend/licensing/licensing.go:123 +0x29c
```

## Your Environment

* Sensu version used: I'm not sure, will provide given the command to get tot
* Active Sensu extensions (e.g. WizardVan 0.1.0): none
* Operating System and version (e.g. Ubuntu 14.04): 18.04
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2) : same as first point

Thx for your help

**Comment by cwartel** [comment]
Hello there, can someone tell me if this issue will be addressed ?
Thank you

**Comment by raffraffraff** [comment]
@cwartel this issue should be logged against the sensu-go project (https://github.com/sensu/sensu-go/issues) because this one is the legacy Sensu 1.x (which is written in Ruby)

**Comment by cwartel** [comment]
Thx @raffraffraff . Sorry for the mistake.
