### ISSUE TITLE
Client crashes continuously on Windows host

### ISSUE THREAD

**Issue by milosgajdos83** [sensu/sensu#759]
After restarting sensu-client on all of our Windows boxes, it crashed and never started back up again. The error it spits out is as follows:

```
{"timestamp":"2014-07-10T17:30:10.686906+0000","level":"warn","message":"config file applied changes","config_file":"C:/etc/sensu/conf.d/checks/service_check.json","changes":{"checks":{"service_check":[null,{"command":"C:\\etc\\sensu/plugins/http/check-http.rb -h localhost -p /api/version","handlers":["default"],"standalone":true,"interval":60}]}}}
{"timestamp":"2014-07-10T17:30:10.686906+0000","level":"warn","message":"config file applied changes","config_file":"C:/etc/sensu/conf.d/client.json","changes":{"client":[null,{"name":"win-compare-prod02","address":"XXXXXXX","subscriptions":["all"]}]}}
{"timestamp":"2014-07-10T17:30:10.686906+0000","level":"info","message":"loaded extension","type":"mutator","name":"only_check_output","description":"returns check output"}
{"timestamp":"2014-07-10T17:30:10.686906+0000","level":"info","message":"loaded extension","type":"handler","name":"debug","description":"outputs json event data"}
C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3-x86-mingw32/lib/eventmachine.rb:859:in `open_udp_socket': no datagram socket (RuntimeError)
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3-x86-mingw32/lib/eventmachine.rb:859:in `open_datagram_socket'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/lib/sensu/client.rb:257:in `setup_sockets'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/lib/sensu/client.rb:293:in `start'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/lib/sensu/client.rb:13:in `block in run'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3-x86-mingw32/lib/eventmachine.rb:187:in `call'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3-x86-mingw32/lib/eventmachine.rb:187:in `run_machine'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3-x86-mingw32/lib/eventmachine.rb:187:in `run'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/lib/sensu/client.rb:12:in `run'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/bin/sensu-client:10:in `<top (required)>'
	from C:/opt/sensu/embedded/bin/sensu-client:23:in `load'
	from C:/opt/sensu/embedded/bin/sensu-client:23:in `<main>'
```

sensu-client version: 0.12.6-4
Windows version: 2008 R2

Configuration is very simple and was working fine until we restarted the client :-)

config.json:
```
{
  "rabbitmq": {
    "host": "XXXXX",
    "port": 5671,
    "vhost": "/sensu",
    "user": "sensu",
    "password": "XXXXXX",
    "ssl": {
      "cert_chain_file": "C:\\etc\\sensu\\ssl\\cert.pem",
      "private_key_file": "C:\\etc\\sensu\\ssl\\key.pem"
    }
  },
  "redis": {
    "host": "XXXXX",
    "port": 6379
  },
  "api": {
    "host": "XXXXX",
    "bind": "0.0.0.0",
    "port": 4567
  }
}
```
client.json:
```
{
  "client": {
    "name": "win-prod02",
    "address": "XXXXX",
    "subscriptions": [
      "all"
    ]
  }
}
```

The way we came across this was when we tried to simulate the crash of the host. We stopped sensu-client like this:

```
net stop sensu-client
```

The alert was raised properly but we were never able to bring the service back up.

**Comment by calebhailey** [comment]
Closing due to inactivity, and because following links to the related issues/PRs is showing related resolutions. Please feel free to create a new issue if this matter is not resolved. #monitoringlove
