### ISSUE TITLE
sensu-api & sensu-client crashes 

### ISSUE THREAD

**Issue by xnulinu** [sensu/sensu#768]
Sensu version -  0.13.1-1
OS - Debian Wheezy

I am running in the situation where the sensu-api crashes with error below; 

{"timestamp":"2014-08-07T22:48:52.532198+0000","level":"warn","message":"reconnecting to redis"}
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:785:in `connect_server': no implicit conversion of String into Integer (TypeError)
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:785:in `reconnect'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.3.0/lib/amqp/session.rb:469:in `reconnect'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-1.0.0/lib/sensu/transport/rabbitmq.rb:37:in `block in reconnect'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/em/timers.rb:56:in `call'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/em/timers.rb:56:in `fire'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `call'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.13.1/lib/sensu/api.rb:23:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.13.1/bin/sensu-api:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-api:23:in `load'
	from /opt/sensu/bin/sensu-api:23:in `<main>'

The issue comes on the light with the addition of HAProxy as the connection get timed out. I have added the timeout option pretty high on haproxy still seeing the issues. It will be better to catch this error then crashing the sensu-client and sensu-api. Let me know what you think about it.

**Comment by calebhailey** [comment]
Closing due to inactivity. Please feel free to create a new issue if this matter is not resolved. #monitoringlove
