### ISSUE TITLE
Intermittent build failure: unexpected token at 'te"}'

### ISSUE THREAD

**Issue by simondean** [sensu/sensu#781]
Hi.  I'm seeing an intermittent failure with a test in the `spec/server_spec.rb` specs:

```
bundle exec rspec spec/server_spec.rb 
.................F.......

Failures:

  1) Sensu::Server can consume results
     Failure/Error: expect(MultiJson.load(latest_event_file)).to eq(event)
     MultiJson::ParseError:
       784: unexpected token at 'te"}'
     # ./spec/server_spec.rb:419:in `block (8 levels) in <top (required)>'
     # ./spec/helpers.rb:62:in `async_wrapper'
     # ./spec/server_spec.rb:400:in `block (2 levels) in <top (required)>'

Finished in 17.24 seconds (files took 0.53367 seconds to load)
25 examples, 1 failure

Failed examples:

rspec ./spec/server_spec.rb:399 # Sensu::Server can consume results
```

The test fails when it attemps to parse the contents of the file `/tmp/sensu-event.json`.  Here is an example of the contents of that file when it fails:

``` json
{"id":"ccc6561b-0fb5-4dbb-851f-d7e6bdfa2808","client":{"name":"i-424242","address":"127.0.0.1","subscriptions":["test"],"keepalive":{"thresholds":{"warning":60,"critical":120}}},"check":{"name":"test","command":"echo WARNING && exit 1","issued":1410026252,"output":"WARNING","status":1,"history":["1"]},"occurrences":1,"action":"create"}te"}
```

See the invalid sequence `te"}` at the end of the JSON.  

Here's the contents of the file when the test passes: 

``` json
{"id":"565783af-c998-4781-80cd-a9ea234cdeea","client":{"name":"i-424242","address":"127.0.0.1","subscriptions":["test"],"keepalive":{"thresholds":{"warning":60,"critical":120}}},"check":{"name":"test","command":"echo WARNING && exit 1","issued":1410026232,"output":"WARNING","status":1,"history":["1","1"]},"occurrences":2,"action":"create"}
```

The difference between the two contents of `/tmp/sensu-event.json` is the JSON is shorter in the failed case because it contains `"history":["1"]` whereas when the test passes the JSON contains  `"history":["1","1"]`.  I think the file is being overritten by successive tests whereas it needs to be truncated.  My guess is the `te"}` is bleed over from a previous test case / test run.

**Comment by calebhailey** [comment]
Closing due to inactivity, and because it looks like the PR fix for this was merged ages ago. Please feel free to create a new issue if this matter is not resolved. #monitoringlove
