### ISSUE TITLE
multijson UTF8 encoding issue

### ISSUE THREAD

**Issue by failshell** [sensu/sensu#783]
Some of our clients are french edition Windows 2008R2 servers. They sometimes returns strings containing accents.

It seems multijson is unable to parse them.

~~~
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/multi_json-1.10.1/lib/multi_json/adapters/yajl.rb:11:in `parse': lexical error: invalid bytes in UTF8 string. (MultiJson::ParseError)
           Le processus ne peut pas acc�der au fichier car ce fichier
                     (right here) ------^
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/multi_json-1.10.1/lib/multi_json/adapters/yajl.rb:11:in `load'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/multi_json-1.10.1/lib/multi_json/adapter.rb:20:in `load'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/multi_json-1.10.1/lib/multi_json.rb:119:in `load'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.13.1/lib/sensu/server.rb:450:in `block in setup_results'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.3.0/lib/amqp/consumer.rb:167:in `call'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.3.0/lib/amqp/consumer.rb:167:in `block in on_delivery'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.3.0/lib/amqp/callbacks.rb:37:in `call'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.3.0/lib/amqp/callbacks.rb:37:in `block in exec_callback'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.3.0/lib/amqp/callbacks.rb:37:in `each'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.3.0/lib/amqp/callbacks.rb:37:in `exec_callback'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.3.0/lib/amqp/consumer.rb:299:in `handle_delivery'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.3.0/lib/amqp/consumer.rb:345:in `block in <class:Consumer>'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.3.0/lib/amqp/session.rb:947:in `call'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.3.0/lib/amqp/session.rb:947:in `receive_frameset'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.3.0/lib/amqp/session.rb:921:in `receive_frame'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.3.0/lib/amqp/session.rb:659:in `receive_data'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.13.1/lib/sensu/server.rb:13:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.13.1/bin/sensu-server:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-server:23:in `load'
	from /opt/sensu/bin/sensu-server:23:in `<main>'
~~~

sensu-server dies and so does sensu-api at that point.

**Comment by calebhailey** [comment]
Closing due to inactivity, and because [Sensu just ditched MultiJSON in 0.23][1]. Please feel free to create a new issue if this matter is not resolved. #monitoringlove

[1]: https://sensuapp.org/docs/0.23/changelog
