### ISSUE TITLE
Sensu client fails to start on Windows

### ISSUE THREAD

**Issue by akurdyukov** [sensu/sensu#791]
I installed sensu-0.13.1 MSI omnibus package on clear Win7. After configuring I have exception in logs
```
{"timestamp":"2014-09-23T00:42:35.084185-0700","level":"warn","message":"loading config files from directory","directory":"C:\\opt\\sensu\\conf.d"}
{"timestamp":"2014-09-23T00:42:35.084185-0700","level":"warn","message":"loading config file","file":"C:/opt/sensu/conf.d/client.json"}
C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0-x86-mingw32/lib/em/connection.rb:419:in `set_tls_parms': wrong number of arguments (6 for 4) (ArgumentError)
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0-x86-mingw32/lib/em/connection.rb:419:in `start_tls'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.3.0/lib/amqp/session.rb:1154:in `upgrade_to_tls_if_necessary'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.3.0/lib/amqp/session.rb:571:in `post_init'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0-x86-mingw32/lib/em/connection.rb:58:in `block in new'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0-x86-mingw32/lib/em/connection.rb:49:in `instance_eval'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0-x86-mingw32/lib/em/connection.rb:49:in `new'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0-x86-mingw32/lib/eventmachine.rb:679:in `bind_connect'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0-x86-mingw32/lib/eventmachine.rb:649:in `connect'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.3.0/lib/amqp/session.rb:445:in `connect'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.3.0/lib/amqp.rb:242:in `connect'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-1.0.0/lib/sensu/transport/rabbitmq.rb:17:in `connect'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-1.0.0/lib/sensu/transport.rb:22:in `connect'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.13.1/lib/sensu/daemon.rb:133:in `setup_transport'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.13.1/lib/sensu/client.rb:244:in `start'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.13.1/lib/sensu/client.rb:13:in `block in run'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0-x86-mingw32/lib/eventmachine.rb:187:in `call'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0-x86-mingw32/lib/eventmachine.rb:187:in `run_machine'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0-x86-mingw32/lib/eventmachine.rb:187:in `run'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.13.1/lib/sensu/client.rb:12:in `run'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.13.1/bin/sensu-client:10:in `<top (required)>'
	from C:/opt/sensu/embedded/bin/sensu-client:23:in `load'
	from C:/opt/sensu/embedded/bin/sensu-client:23:in `<main>'
```

Problem line says
```
      EventMachine::set_tls_parms(@signature, priv_key || '', cert_chain || '', verify_peer, (use_tls ? true : false), cipher_list || '')
```
after changing into
```
      EventMachine::set_tls_parms(@signature, priv_key || '', cert_chain || '', verify_peer)
```
it seems to work. But I have no idea why standard EM is used, not the packaged with sensu-em gem.

**Comment by runningman84** [comment]
is this solved in 0.16?
