### ISSUE TITLE
sensu-api process dies after 'reconnecting to redis'

### ISSUE THREAD

**Issue by neilprosser** [sensu/sensu#836]
I've had this issue a few times now. The sensu-api process dies on both instances where sensu-server and sensu-api are running within a few seconds of each other. It's definitely possible that Redis has disappeared for some reason but I'm wondering whether it should die like that.

The instances are running in EC2 and they are connected to an Elasticache Redis instance. If I restart the sensu-api service on those instances it comes back and is fine.

This is the last output in the log (I've enabled `debug` logging but this is all I get).

```
{"timestamp":"2014-12-22T14:50:48.380867+0000","level":"warn","message":"reconnecting to redis"}
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/multi_json-1.10.1/lib/multi_json/adapter.rb:19:in `load': Yajl::ParseError (MultiJson::ParseError)
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/multi_json-1.10.1/lib/multi_json.rb:119:in `load'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/lib/sensu/api.rb:313:in `block (4 levels) in <class:API>'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-0.5.0/lib/em-redis/redis_protocol.rb:457:in `call'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-0.5.0/lib/em-redis/redis_protocol.rb:457:in `dispatch_response'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-0.5.0/lib/em-redis/redis_protocol.rb:411:in `process_cmd'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-0.5.0/lib/em-redis/redis_protocol.rb:385:in `receive_data'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/lib/sensu/api.rb:23:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/bin/sensu-api:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-api:23:in `load'
        from /opt/sensu/bin/sensu-api:23:in `<main>'
```

**Comment by bimlendu** [comment]
This happens in my setup as well, when I delete a client key in redis. 

I running the latest sensu package 0.18.0.

**Comment by neilprosser** [comment]
This still happens with 0.19.2

```
{"timestamp":"2015-07-01T10:08:31.876008+0000","level":"warn","message":"reconnecting to redis"}
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/multi_json-1.11.0/lib/multi_json/adapter.rb:19:in `load': Yajl::ParseError (MultiJson::ParseError)
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/multi_json-1.11.0/lib/multi_json.rb:119:in `load'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.19.2/lib/sensu/api/process.rb:337:in `block (4 levels) in <class:Process>'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:489:in `call'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:489:in `dispatch_response'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:434:in `process_cmd'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/em-redis-unified-1.0.0/lib/em-redis/redis_protocol.rb:408:in `receive_data'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.19.2/lib/sensu/api/process.rb:24:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.19.2/bin/sensu-api:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-api:23:in `load'
        from /opt/sensu/bin/sensu-api:23:in `<main>'
```

**Comment by dreamerz** [comment]
@bimlendu 
If you delete client key in redis directly, you have to remove that client key from a "clients" set.
```
SREM clients client
```
In sensu-api codes, you can see it remove client from clients set first then delete the rest of client data.
https://github.com/sensu/sensu/blob/master/lib/sensu/api/process.rb#L404-L415

**Comment by lukedemi** [comment]
Experiencing this exact issue as well, first began to occur when I started deleting clients using sensu-api REST calls.
