### ISSUE TITLE
Can't restart because 'no datagram socket'

### ISSUE THREAD

**Issue by Onlinehead** [sensu/sensu#862]
Hi!
In CentOS 6, when we restart sensu by puppet recipe (after configs changed), sensu-client can't start with error in log:
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:868:in `open_udp_socket': no datagram socket (RuntimeError)
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:868:in `open_datagram_socket'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/lib/sensu/client.rb:226:in `setup_sockets'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/lib/sensu/client.rb:255:in `start'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/lib/sensu/client.rb:13:in `block in run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `call'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/lib/sensu/client.rb:12:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/bin/sensu-client:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-client:23:in `load'
	from /opt/sensu/bin/sensu-client:23:in `<main>

**Comment by fujin** [comment]
:+1: Just hit this in our F20 infrastructure. It appears that Sensu leaked a file descriptor for the 3030 UDP listen socket to one of the child processes, which wasn't reaped during a restart of the parent, which prevented the new process from starting. cc/ @joemiller

**Comment by joemiller** [comment]
I think we ran into this today as well, and I think we know why.

In our case, we have a very long-running sensu check (5-20mins, depending on host.. not ideal). We happened to hit a moment today when our chef procs issued a sensu-client restart, but that long-running check was underway and ignored the TERM signal. sensu-client eventually exited but when the new process tried to fork it could not bind to UDP :3030 because the long-running check had it open.

I think the fix might be to close fd's and not leak them to children?

Here are some relevant cut n pastes from our observation today:

```
[root@endpoint6f44e9c7 ~]# systemctl status sensu-client
sensu-client.service - sensu client
   Loaded: loaded (/etc/systemd/system/sensu-client.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2015-02-17 23:16:32 UTC; 13s ago
  Process: 24749 ExecStart=/opt/sensu/bin/sensu-client -c /etc/sensu/config.json -d /etc/sensu/conf.d -e /etc/sensu/extensions -l /var/log/sensu/sensu-client.log (code=exited, status=1/FAILURE)
 Main PID: 24749 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/sensu-client.service
           ├─16009 sudo /etc/sensu/plugins/check-rpm-verify.rb 
           ├─16010 /usr/bin/ruby-mri /etc/sensu/plugins/check-rpm-verify.rb 
           ├─16012 sh -c rpm -V --all 2>&1
           └─16013 rpm -V --all

^C

[root@endpoint6f44e9c7 ~]# tail -f /var/log/sensu/sensu-client.log
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/lib/sensu/client.rb:226:in `setup_sockets'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/lib/sensu/client.rb:255:in `start'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/lib/sensu/client.rb:13:in `block in run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `call'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/lib/sensu/client.rb:12:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/bin/sensu-client:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-client:23:in `load'
	from /opt/sensu/bin/sensu-client:23:in `<main>'


^C
[root@endpoint6f44e9c7 ~]# ps aux | grep sensu
root     16009  0.0  0.0 187108  2656 ?        S    23:06   0:00 sudo /etc/sensu/plugins/check-rpm-verify.rb 
root     16010  0.1  0.1 138276  9368 ?        Sl   23:06   0:00 /usr/bin/ruby-mri /etc/sensu/plugins/check-rpm-verify.rb


[root@endpoint6f44e9c7 ~]# lsof -n -P | grep 3030
sudo      16009                                   root   11u     IPv4          642838877       0t0        UDP 127.0.0.1:3030

[root@endpoint6f44e9c7 ~]# rpm -q sensu
sensu-0.16.0-1.x86_64
```

**Comment by benh57** [comment]
Also written up here: https://github.com/sensu/sensu-build/issues/95

**Comment by portertech** [comment]
Same/similar issue as https://github.com/sensu/sensu/issues/759

The socket `close()` was never added to the client `stop()`, or was lost during refactoring https://github.com/sensu/sensu/blob/master/lib/sensu/client/process.rb#L413 I can put together a PR for this shortly, as it should help.

I do not believe EM supports `SO_REUSEADDR` and `SO_REUSEPORT` :-1: Will investigate further.

Sean.

**Comment by portertech** [comment]
@robx interesting EM patch, we could test it w/ https://github.com/sensu/sensu-em unclear if we are sticking w/ the fork, as upstream has seen several improvements, just not the ones we needed.

**Comment by portertech** [comment]
https://github.com/sensu/sensu/pull/928

**Comment by robx** [comment]
@portertech I ported the patch to the sensu em fork, thanks for the heads-up. Upstream eventmachine seems to be... resting.

**Comment by sodabrew** [comment]
Oh hey, I just noticed your fork of EM. Let's see what we can do to avoid the need for that for too long? That said, I'm not sure if this is an appropriate change in all cases - discuss on eventmachine/eventmachine#591 ?

**Comment by calebhailey** [comment]
Closing due to inactivity, and because it looks like all the related PRs have been merged. Please feel free to create a new issue if this matter is not resolved. #monitoringlove
