### ISSUE TITLE
CI tests randomly failing

### ISSUE THREAD

**Issue by davent** [sensu/sensu#876]
One of the Travis CI tests are randomly failing due to the test result sometimes only having 1 occurrence. This appears to be happening randomly across all Ruby versions. Forcing a re-test by closing and re-opening the pull request several times will eventually result in a pass.

Log from one of the failed runs:
```
Using worker: worker-linux-3da96de7-1.bb.travis-ci.org:travis-linux-2

Build system information
Build language: ruby
Build image provisioning date and time
Wed Feb  4 18:22:50 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04 LTS
Release:	12.04
Codename:	precise
Linux Version
2.6.32-042stab090.5
Cookbooks Version
23bb455 https://github.com/travis-ci/travis-cookbooks/tree/23bb455
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
Cassandra version
2.0.9
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-042stab090.5", arch: "amd64", family: "unix"

$ git clone --depth=50 git://github.com/sensu/sensu.git sensu/sensu
Cloning into 'sensu/sensu'...
remote: Counting objects: 862, done.
remote: Compressing objects: 100% (428/428), done.
remote: Total 862 (delta 511), reused 746 (delta 427), pack-reused 0
Receiving objects: 100% (862/862), 168.73 KiB | 0 bytes/s, done.
Resolving deltas: 100% (511/511), done.
Checking connectivity... done.
$ cd sensu/sensu
$ git fetch origin +refs/pull/875/merge:
remote: Counting objects: 6, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 6 (delta 3), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (6/6), done.
From git://github.com/sensu/sensu
 * branch            refs/pull/875/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
$ sudo service rabbitmq-server start
[ OK ]
$ sudo service redis-server start
redis-server start/running, process 2655

Setting environment variables from .travis.yml
$ export RACK_ENV=development

$ rvm use 1.9.3 --install --binary --fuzzy
Using /home/travis/.rvm/gems/ruby-1.9.3-p551
$ export BUNDLE_GEMFILE=$PWD/Gemfile
$ ruby --version
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]
$ rvm --version
rvm 1.26.10 (latest-minor) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
$ bundle --version
Bundler version 1.7.6
$ gem --version
2.4.5
$ gem update --system 2.1.11
Updating rubygems-update
Fetching: rubygems-update-2.1.11.gem (100%)
Successfully installed rubygems-update-2.1.11
Installing RubyGems 2.1.11
RubyGems 2.1.11 installed



------------------------------------------------------------------------------

RubyGems installed the following executables:
	/home/travis/.rvm/rubies/ruby-1.9.3-p551/bin/gem

RubyGems system software updated
$ gem --version
2.1.11
$ bundle install --jobs=3 --retry=3
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Installing addressable 2.3.7
Installing rake 10.4.2
Installing amq-protocol 1.9.2
Installing rack 1.6.0
Installing tilt 1.4.1
Installing ffi 1.9.6
Installing cookiejar 0.3.2
Installing daemons 1.1.9
Installing diff-lcs 1.2.5
Installing eventmachine 1.0.7
Installing http_parser.rb 0.6.0
Installing multi_json 1.10.1
Installing rspec-support 3.0.4
Installing uuidtools 2.1.4
Using bundler 1.7.6
Installing rack-protection 1.5.3
Installing childprocess 0.5.3
Installing amqp 1.5.0
Installing em-socksify 0.3.0
Installing em-redis-unified 0.5.0
Installing em-worker 0.0.2
Installing thin 1.5.0
Installing sensu-settings 1.2.0
Installing rspec-core 3.0.4
Installing rspec-expectations 3.0.4
Installing rspec-mocks 3.0.4
Installing sinatra 1.3.5
Installing em-http-request 1.1.2
Installing rspec 3.0.0
Installing async_sinatra 1.0.0
Installing sensu-em 2.4.1
Installing sensu-logger 1.0.0
Installing sensu-extension 1.0.0
Installing sensu-transport 2.4.0
Installing sensu-spawn 1.1.0
Installing sensu-extensions 1.0.0
Using sensu 0.17.0.beta from source at .
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
$ bundle exec rake
/home/travis/.rvm/rubies/ruby-1.9.3-p551/bin/ruby -I/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.4/lib:/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rspec-support-3.0.4/lib -S /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.4/exe/rspec ./spec/api_spec.rb ./spec/cli_spec.rb ./spec/client_spec.rb ./spec/daemon_spec.rb ./spec/server_spec.rb ./spec/socket_spec.rb ./spec/utilities_spec.rb
..................................................................................F.............................

Failures:

  1) Sensu::Server can consume results
     Failure/Error: expect(event[:occurrences]).to eq(2)
       
       expected: 2
            got: 1
       
       (compared using ==)
     # ./spec/server_spec.rb:419:in `block (8 levels) in <top (required)>'
     # ./spec/helpers.rb:62:in `async_wrapper'
     # ./spec/server_spec.rb:403:in `block (2 levels) in <top (required)>'

Finished in 54.56 seconds (files took 0.59775 seconds to load)
112 examples, 1 failure

Failed examples:

rspec ./spec/server_spec.rb:402 # Sensu::Server can consume results
/home/travis/.rvm/rubies/ruby-1.9.3-p551/bin/ruby -I/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.4/lib:/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rspec-support-3.0.4/lib -S /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/rspec-core-3.0.4/exe/rspec ./spec/api_spec.rb ./spec/cli_spec.rb ./spec/client_spec.rb ./spec/daemon_spec.rb ./spec/server_spec.rb ./spec/socket_spec.rb ./spec/utilities_spec.rb failed

The command "bundle exec rake" exited with 1.

Done. Your build exited with 1.
```

**Comment by portertech** [comment]
If you increase the timer in the test, to wait another second, does this failure continue? Is it simply the async action taking too long on your CI machine?

**Comment by davent** [comment]
This is not running on my machine. These tests were part of the automated Travis CI test run as part of a Pull Request.

**Comment by southwolf** [comment]
CI also fails in my PR #905 .

**Comment by portertech** [comment]
Because some of the tests use timers due to the inability to nest enough callbacks, build boxes w/ significant load may experience these issues. e.g. It takes time for a message to be published to RabbitMQ and then consumed and processed.

**Comment by portertech** [comment]
I usually kick the travis job on PRs eligible for merging.

**Comment by calebhailey** [comment]
Closing due to inactivity. Please feel free to create a new issue if this matter is not resolved. #monitoringlove
