### ISSUE TITLE
sensu-client fails to start when DNS is temporarily unavailable

### ISSUE THREAD

**Issue by terrorobe** [sensu/sensu#877]
Broker connection should be decoupled from daemonizing and be retried indefinitely

```
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:673:in `connect_server': unable to resolve server address (EventMachine::ConnectionError)
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:673:in `bind_connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:649:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/session.rb:457:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp.rb:242:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-2.4.0/lib/sensu/transport/rabbitmq.rb:118:in `setup_connection'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-2.4.0/lib/sensu/transport/rabbitmq.rb:147:in `connect_with_eligible_options'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-2.4.0/lib/sensu/transport/rabbitmq.rb:14:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-2.4.0/lib/sensu/transport.rb:22:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/lib/sensu/daemon.rb:133:in `setup_transport'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/lib/sensu/client.rb:254:in `start'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/lib/sensu/client.rb:13:in `block in run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `call'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.0/lib/eventmachine.rb:187:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/lib/sensu/client.rb:12:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.16.0/bin/sensu-client:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-client:23:in `load'
	from /opt/sensu/bin/sensu-client:23:in `<main>'

Error: Could not start Service[sensu-client]: Execution of '/etc/init.d/sensu-client start' returned 1: * Starting sensu-client
   ...fail!
Wrapped exception:
Execution of '/etc/init.d/sensu-client start' returned 1: * Starting sensu-client
   ...fail!
Error: /Stage[main]/Sensu::Client::Service/Service[sensu-client]/ensure: change from stopped to running failed: Could not start Service[sensu-client]: Execution of '/etc/init.d/sensu-client start' returned 1: * Starting sensu-client
   ...fail!
```

**Comment by portertech** [comment]
The Sensu transport should continue its attempts to connect to the transport, however, it looks like the `EventMachine::ConnectionError` is being raised outside of the rescue/catch, causing it to throw an exception instead of reconnect. We will investigate further this afternoon.

**Comment by terrorobe** [comment]
Thanks a bunch!

Not a huge issue but anything that makes sensu more reliable and dependable without resorting to external daemon management tools is a good thing.

**Comment by iiro** [comment]
Hi,

anything new regarding this one? Having these problems from time to time...

**Comment by jbfarez** [comment]
Hello there, I've just faced a similar issue with name resolution. If the reverse DNS is not exactly the same as the hostname, the transport layer enter in a loop :

```{"timestamp":"2015-09-11T12:52:51.109182+0200","level":"warn","message":"reconnecting to transport"}```

Then nothing more happen ...
Okay, this shouldn't happening (DNS differ that hostname) but ... if it does, you will not have monitoring anymore :-(

**Comment by iiro** [comment]
Anything new...?

**Comment by portertech** [comment]
@jbfarez looks like the Ruby process cached the DNS result and then continues to attempt to reconnect. 

We should look into using an async DNS hostname lookup prior to attempting to reconnect, perhaps with http://www.rubydoc.info/github/eventmachine/eventmachine/EventMachine/DNS/Resolver, and make multiple attempts to resolve it successfully.

We recommend not using a hostname for Sensu connection configuration at this time, please use an IP address as it does not require resolution, which is a potential point of failure.

**Comment by jbfarez** [comment]
Hi @portertech, okay, good to know.

About the IP use, I'll do it this way but it's a bit less dynamic ;-)

Thanks for your reply.

Cheers.

**Comment by portertech** [comment]
https://github.com/eventmachine/eventmachine/blob/master/lib/em/resolver.rb

**Comment by EslamElHusseiny** [comment]
Is this issue still exist ?

**Comment by yanc0** [comment]
I'm facing to this bug too.
```
{"timestamp":"2016-02-07T03:07:51.842427+0100","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/rabbitmq.json","changes":{"rabbitmq":[null,{"ssl":{"cert_chain_file":"/etc/sensu/ssl/cert.pem","private_key_file":"/etc/sensu/ssl/key.pem"},"host":"collector.skale-5.io","port":5671,"user":"sensu","password":"REDACTED","vhost":"/sensu"}]}}
{"timestamp":"2016-02-07T03:07:51.847274+0100","level":"warn","message":"loading extension files from directory","directory":"/etc/sensu/extensions"}
/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:681:in `connect_server': unable to resolve server address (EventMachine::ConnectionError)
	from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:681:in `bind_connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:657:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/amqp-1.5.0/lib/amqp/session.rb:457:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/amqp-1.5.0/lib/amqp.rb:242:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-transport-3.3.0/lib/sensu/transport/rabbitmq.rb:119:in `setup_connection'
	from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-transport-3.3.0/lib/sensu/transport/rabbitmq.rb:148:in `connect_with_eligible_options'
	from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-transport-3.3.0/lib/sensu/transport/rabbitmq.rb:15:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-transport-3.3.0/lib/sensu/transport.rb:22:in `connect'
	from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-0.21.0/lib/sensu/daemon.rb:187:in `setup_transport'
	from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-0.21.0/lib/sensu/client/process.rb:412:in `start'
	from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-0.21.0/lib/sensu/client/process.rb:19:in `block in run'
	from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `call'
	from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-0.21.0/lib/sensu/client/process.rb:18:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-0.21.0/exe/sensu-client:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-client:23:in `load'
	from /opt/sensu/bin/sensu-client:23:in `<main>'
```

The sensu-client stops working and didn't restarts causing a keepalive alert.

**Comment by EslamElHusseiny** [comment]
@yanc0 double check  the rabbitmq hostname configured in sensu-client is resolvable

**Comment by yanc0** [comment]
Yeah It is, but It seems that sometimes a DNS resolution problem occurs, the sensu client entirely fails and it does not retry. I manually restarted sensu-client and there is no problem anymore.

**Comment by yanc0** [comment]
The problem occurs again this morning, on different host but on the same hosting provider. It causes keepalive problem an triggers our alerting system. Maybe they have DNS instability but the sensu-client have to be robust against this problem.

**Comment by calebhailey** [comment]
@terrorobe @yanc0 hi there! Sorry for the radio silence on this one. 

There have been several new enhancements to the Sensu transport in the latest Sensu releases (multiple 0.22 releases, and a 0.23 release), as well as an upgrade to the underlying Ruby (upgraded to 2.3) in [Sensu 0.23][1], so I'm going to presumptively close this issue. Please feel free to open a new issue if this problem persists. 

#monitoringlove 

[1]: https://sensuapp.org/docs/0.23/changelog
