### ISSUE TITLE
Windows Sensu 0.17.0.beta-1 fails to start

### ISSUE THREAD

**Issue by pgporada** [sensu/sensu#883]
I'm trying to install the latest beta on a fresh Windows VM. When I start the sensu-client service, this is what I receive in the sensu error log on the VM.
```
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- 2.0/rubyeventmachine (LoadError)
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.1-x86-mingw32/lib/rubyeventmachine.rb:2:in `<top (required)>'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-em-2.4.1-x86-mingw32/lib/eventmachine.rb:8:in `<top (required)>'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-logger-1.0.0/lib/sensu/logger/stream.rb:3:in `<top (required)>'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-logger-1.0.0/lib/sensu/logger.rb:1:in `<top (required)>'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.17.0.beta/lib/sensu/daemon.rb:16:in `<top (required)>'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.17.0.beta/lib/sensu/client.rb:1:in `<top (required)>'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.17.0.beta/bin/sensu-client:7:in `<top (required)>'
	from C:/opt/sensu/embedded/bin/sensu-client:23:in `load'
	from C:/opt/sensu/embedded/bin/sensu-client:23:in `<main>'
```

**Comment by ricardozd** [comment]
Hello,

I used this version too and I is exactly the same. I install the version 0.14 but i have a problem... At times my checks print : Unexpected error: The parameter is incorrect. (87) ... only keepalive it's ok always... any idea for fix?

**Comment by portertech** [comment]
@pgporada @ricardozd I just replaced the defunct beta MSI, please try the latest build http://repos.sensuapp.org/msi/sensu-0.17.0.beta-1.msi

**Comment by ricardozd** [comment]
Thanks, I will try!

**Comment by ricardozd** [comment]
The sensu-0.17.beta it's works but I still have the same problem. I will the open new issue.

**Comment by pgporada** [comment]
@portertech 
With the sensu-0.17.0.beta.1-1.msi I was able to successfully start the sensu-client on my Windows 7 64bit VM and get the sensu-client to appear in Uchiwa. I am using RabbitMQ with SSL only. I hope that this message will help others.

**Comment by portertech** [comment]
The Sensu 0.17.0.beta.1-1 MSI is available and has the fix for this issue: http://repos.sensuapp.org/msi/sensu-0.17.0.beta.1-1.msi
