### ISSUE TITLE
transport connected false running bundle exec rake within docker container

### ISSUE THREAD

**Issue by priya-seth** [sensu/sensu#907]
Hi,

I am using the latest sensu source and trying to run the bundle exec rake command within a docker container. It fails with the following error:
Failures:

  1) Sensu::API::Process can provide basic version and health information
     Failure/Error: expect(body[:transport][:connected]).to be(true)

       expected true
            got false
     # ./spec/api/process_spec.rb:49:in `block (4 levels) in <top (required)>'
     # ./spec/helpers.rb:159:in `call'
     # ./spec/helpers.rb:159:in `block in api_request'
     # ./spec/helpers.rb:56:in `async_wrapper'
     # ./spec/helpers.rb:69:in `api_test'
     # ./spec/api/process_spec.rb:44:in `block (2 levels) in <top (required)>'

Finished in 1 minute 4.47 seconds (files took 0.33639 seconds to load)
117 examples, 1 failure
RabbitMQ and Reddis servers are up and running before issuing the command. This is on Ubuntu 14.10. The same command passes outside the container with the same configuration.

Has anyone seen this issue before? Thanks in advance.

Regards,
Priya

**Comment by portertech** [comment]
Did the API have access to RabbitMQ from within the container?

**Comment by calebhailey** [comment]
Closing due to inactivity. Please feel free to create a new issue if this matter is not resolved. #monitoringlove
