### ISSUE TITLE
MultiJson::ParseError running bundle exce rake on RHEL 7.1

### ISSUE THREAD

**Issue by seth-osc** [sensu/sensu#938]
Hi,

I have followed the following steps:
- git clone https://github.com/sensu/sensu
- bundle install --path vendor/bundle
- bundle exec rake

on RHEL 7.1 x86_64 architecture and I am getting the following error/ test case failure:

/usr/bin/ruby -I/home/sensu/sensu/vendor/bundle/ruby/gems/rspec-core-3.0.4/lib:/home/sensu/sensu/vendor/bundle/ruby/gems/rspec-support-3.0.4/lib -S /home/sensu/sensu/vendor/bundle/ruby/gems/rspec-core-3.0.4/exe/rspec ./spec/api/process_spec.rb ./spec/cli_spec.rb ./spec/client/process_spec.rb ./spec/client/socket_spec.rb ./spec/daemon_spec.rb ./spec/server/filter_spec.rb ./spec/server/handle_spec.rb ./spec/server/mutate_spec.rb ./spec/server/process_spec.rb ./spec/utilities_spec.rb
[WARNING] MultiJson is using the default adapter (ok_json).We recommend loading a different JSON library to improve performance.
...................................................................................................F.....................

Failures:

  1) Sensu::Server::Mutate can mutate event data
     Failure/Error: expect(MultiJson.load(event_data)).to include(:mutated)
     MultiJson::ParseError:
       invalid character at "WARNING] M"
     # ./spec/server/mutate_spec.rb:38:in `block (6 levels) in <top (required)>'
     # ./lib/sensu/server/mutate.rb:19:in `call'
     # ./lib/sensu/server/mutate.rb:19:in `block in mutator_callback'
     # ./spec/helpers.rb:56:in `async_wrapper'
     # ./spec/server/mutate_spec.rb:14:in `block (2 levels) in <top (required)>'

Finished in 1 minute 13.62 seconds (files took 0.50917 seconds to load)
121 examples, 1 failure

Failed examples:

rspec ./spec/server/mutate_spec.rb:13 # Sensu::Server::Mutate can mutate event data
/usr/bin/ruby -I/home/sensu/sensu/vendor/bundle/ruby/gems/rspec-core-3.0.4/lib:/home/sensu/sensu/vendor/bundle/ruby/gems/rspec-support-3.0.4/lib -S /home/sensu/sensu/vendor/bundle/ruby/gems/rspec-core-3.0.4/exe/rspec ./spec/api/process_spec.rb ./spec/cli_spec.rb ./spec/client/process_spec.rb ./spec/client/socket_spec.rb ./spec/daemon_spec.rb ./spec/server/filter_spec.rb ./spec/server/handle_spec.rb ./spec/server/mutate_spec.rb ./spec/server/process_spec.rb ./spec/utilities_spec.rb failed

The same test case succeeds on Ubuntu 14.10.

Could it be related to the warning:
[WARNING] MultiJson is using the default adapter (ok_json).We recommend loading a different JSON library to improve performance.

Has anyone seen this issue before?

Thanks.

**Comment by portertech** [comment]
What version of ruby are you using? I would seem you are running Ruby 1.8.x, without the availability of a recommended JSON parser, e.g. json gem.

**Comment by seth-osc** [comment]
The ruby version is ruby 2.0.0p598

**Comment by portertech** [comment]
@seth-osc try installing the json gem before running the test again.

**Comment by portertech** [comment]
I wonder if there was a regression in ruby that dropped the included json gem :/

**Comment by calebhailey** [comment]
Closing due to inactivity. Please feel free to create a new issue if this matter is not resolved. #monitoringlove 

FWIW, [Sensu just ditched MultiJSON in 0.23][1] :smile: 

[1]: https://sensuapp.org/docs/0.23/changelog
