### ISSUE TITLE
The connection is closed, you can't use it anymore! (AMQP::ConnectionClosedError)

### ISSUE THREAD

**Issue by alex-leonhardt** [sensu/sensu#994]
Hi,

we've run into a weird error that, when the default gateway goes away for a short time, some of the sensu-clients are dying in an AMQP exception and although the sensu-client keeps running, it will no longer re-connect to AMQP.

```
{"timestamp":"2015-07-10T10:11:16.385175+0000","level":"error","message":"[amqp] Detected missing server heartbeats"}
{"timestamp":"2015-07-10T10:11:16.385368+0000","level":"warn","message":"reconnecting to transport"}
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/session.rb:738:in `send_frame': The connection is closed, you can't use it anymore! (AMQP::ConnectionClosedError)
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/consumer.rb:117:in `block (2 levels) in cancel'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/queue.rb:267:in `call'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/queue.rb:267:in `block in once_declared'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/em/deferrable.rb:48:in `call'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/em/deferrable.rb:48:in `callback'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/queue.rb:264:in `once_declared'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/consumer.rb:116:in `block in cancel'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/channel.rb:936:in `call'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/channel.rb:936:in `block in once_open'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/em/deferrable.rb:48:in `call'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/em/deferrable.rb:48:in `callback'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/channel.rb:933:in `once_open'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/consumer.rb:115:in `cancel'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/queue.rb:831:in `block (2 levels) in unsubscribe'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/queue.rb:1389:in `call'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/queue.rb:1389:in `once_name_is_available'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/queue.rb:829:in `block in unsubscribe'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/channel.rb:936:in `call'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/channel.rb:936:in `block in once_open'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/em/deferrable.rb:48:in `call'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/em/deferrable.rb:48:in `callback'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/channel.rb:933:in `once_open'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/queue.rb:828:in `unsubscribe'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-3.0.0/lib/sensu/transport/rabbitmq.rb:60:in `block in unsubscribe'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-3.0.0/lib/sensu/transport/rabbitmq.rb:58:in `each'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-3.0.0/lib/sensu/transport/rabbitmq.rb:58:in `unsubscribe'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.19.1/lib/sensu/client/process.rb:431:in `pause'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.19.1/lib/sensu/daemon.rb:199:in `block in setup_transport'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-3.0.0/lib/sensu/transport/rabbitmq.rb:20:in `call'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-3.0.0/lib/sensu/transport/rabbitmq.rb:20:in `reconnect'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-transport-3.0.0/lib/sensu/transport/rabbitmq.rb:114:in `block in reconnect_callback'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/callbacks.rb:51:in `call'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/callbacks.rb:51:in `block in exec_callback_yielding_self'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/callbacks.rb:51:in `each'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/callbacks.rb:51:in `exec_callback_yielding_self'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/session.rb:874:in `run_skipped_heartbeats_callbacks'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/session.rb:707:in `handle_skipped_heartbeats'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/amqp-1.5.0/lib/amqp/session.rb:981:in `send_heartbeat'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/em/timers.rb:56:in `call'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/em/timers.rb:56:in `fire'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `call'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.19.1/lib/sensu/client/process.rb:18:in `run'
from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.19.1/bin/sensu-client:10:in `<top (required)>'
from /opt/sensu/bin/sensu-client:23:in `load'
from /opt/sensu/bin/sensu-client:23:in `<main>'
```

The only way to get this back to work is to restart sensu-client manually on the host.

Would it be possible to catch this exception and reset sensu-client's state and re-establish a connection to AMQP ? Or something similar if this doesnt make much sense ? 

Thanks
Alex

**Comment by portertech** [comment]
Hmmm, heartbeat failures should be handle gracefully. I'm concerned about Sensu's use of `eventmachine-1.0.3`, I will investigate the load order.

**Comment by ryancurrah** [comment]
This sounds very similar to what were experiencing is there any update on this?

**Comment by portertech** [comment]
Looks like the heartbeat monitor/sender is still sending a frame after a connection has been closed, while Sensu is reconnecting to RabbitMQ. https://github.com/ruby-amqp/amqp/blob/master/lib/amqp/session.rb#L983

I once patched amq-protocol to address this issue: https://github.com/sensu/sensu-transport/commit/3a9da686d6b8ac380303db6395f1e539c568bd98

I will patch sensu-transport to fix amqp heartbeats while reconnecting and submit a PR to ruby-aqmp/amqp.

**Comment by ryancurrah** [comment]
Cool, when do you think this patch to sensu-transport will make it to sensu-clients?

**Comment by portertech** [comment]
Open PR https://github.com/sensu/sensu-transport/pull/15

**Comment by portertech** [comment]
@ryancurrah there are a few other outstanding issues that are going to lead to a release today or tomorrow.

**Comment by ryancurrah** [comment]
Awesome thanks for quick responses, I look forward to testing the client. I will also post my results here to for anyone else that it is interested.

**Comment by alex-leonhardt** [comment]
Thanks @portertech !
