### ISSUE TITLE
sensu on vyos

### ISSUE THREAD

**Issue by meltonpineda** [sensu/sensu#996]
hi,

I'm planning add vyos router on our my sensu monitoring but i'm having this error. I already installed build-essential and eventmachine still doesn't work.

/var/run/sensu$ tail -f /var/log/sensu/sensu-client.log
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.0/lib/sensu/daemon.rb:187:in `setup_transport'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.0/lib/sensu/client/process.rb:412:in `start'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.0/lib/sensu/client/process.rb:19:in `block in run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `call'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.0/lib/sensu/client/process.rb:18:in `run'
	from /opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.20.0/bin/sensu-client:10:in `<top (required)>'
	from /opt/sensu/bin/sensu-client:23:in `load'
	from /opt/sensu/bin/sensu-client:23:in `<main>'

**Comment by portertech** [comment]
@meltonpineda could you please gist the entire backtrace in the sensu client log?

**Comment by meltonpineda** [comment]
As I reviewed the entire sensu-client log, It turns out that I misplaced the ssl certs. thanks a lot. :)

**Comment by portertech** [comment]
@meltonpineda would it be possible to get that full backtrace here? I would love to improve the error handling to make things easier for users :) If not, no problem, we can then close this one :+1:

**Comment by meltonpineda** [comment]
I would like to share the logs but i'm afraid the previous logs of sensu-client are already deleted. :)

**Comment by calebhailey** [comment]
Closing due to inactivity. Please feel free to create a new issue if this matter is not resolved. #monitoringlove
